### ISSUE TITLE
Feature Request: Source app_secret from strings.xml?

### ISSUE THREAD

**Issue by spacesuitdiver** [microsoft/appcenter-sdk-react-native#511] opened 2019-01-22 03:36 UTC
It's a bit unconventional to have to source a .json files during build time if we want to parameterize (via ENV variables) the app_secret. Usually with other SDK app secrets are put in the strings.xml.

**Comment by guperrot** [comment] 2019-01-28 23:20
We might consider this feature in the future but there is no plan right now.

**Comment by quarryman** [comment] 2020-01-31 13:03
@guperrot what is the best-practice for building beta/production and pushing it to separate appcenter apps from single source?

The issue is clear I guess, one should parametrize json file during build too set proper secret in buildtime

**Comment by guperrot** [comment] 2020-01-31 20:58
@quarryman 

> one should parametrize json file during build too set proper secret in buildtime

That's the best way I can think of.

**Comment by DmitriyKirakosyan** [comment] 2024-04-15 04:30
As we do not have plans to add support for this feature in the next year, I'm closing the issue.

**Closed by DmitriyKirakosyan** 2024-04-15 04:30 UTC
Labels: feature request
