### ISSUE TITLE
RN 0.59 Could not configure AppCenter for iOS.

### ISSUE THREAD

**Issue by v0lume** [Microsoft/AppCenter-SDK-React-Native#545] opened 2019-03-13 21:20 UTC
RN 0.59, facing an error when im trying to run react-native link:

```
Patching file ios/survey/AppDelegate.m
Could not configure AppCenter for iOS. Error Reason - 
        Could not find line "NSURL *jsCodeLocation;" in file AppDelegate.m.
        Update AppDelegate.m so that text is present, as we match on it and insert '  [AppCenterReactNative register];  // Initialize AppCenter ' after for AppCenter SDK integration.

```
![image](https://user-images.githubusercontent.com/5075100/54315173-76d95b80-45ee-11e9-845b-a696c6ba6682.png)

**Fixed by** adding `NSURL *jsCodeLocation;` to AppDelegate.m (after curly braces)

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"survey"
                                            initialProperties:nil];
  NSURL *jsCodeLocation;
```

The same error is with AppCenterAnalytics and AppCenterCrashReports

**Comment by schwamic** [comment] 2019-03-14 18:20
same here!

**Comment by dhei** [comment] 2019-03-14 19:02
Hey @v0lume @schwamic,

Thanks for reporting this issue. It is caused by appcenter react-native linker script not yet compatible with RN v0.59. We're working on a fix and it should be shipped in the coming App Center RN SDK March release.

**Comment by iamclaytonray** [comment] 2019-03-19 00:10
@dhei - when would that release ship? Thanks for all you do! 😄

**Comment by guperrot** [comment] 2019-03-19 00:38
It should be released later this week.

**Comment by dhei** [comment] 2019-03-20 01:24
This bug has been fixed in the [SDK March release](https://github.com/Microsoft/AppCenter-SDK-React-Native/releases/tag/1.13.0).

**Closed by dhei** 2019-03-20 01:24 UTC
Labels: bug
