### ISSUE TITLE
[iOS] React Native stack trace does not show JS lines

### ISSUE THREAD

**Issue by esam091** [microsoft/appcenter-sdk-react-native#248] opened 2018-02-27 03:54 UTC
I have an existing app that I want to integrate with Crashes SDK, but after following the instructions, the JS stack trace is still not showing.

This is what I got from the report instead
<img width="1025" alt="screen shot 2018-02-27 at 10 25 41" src="https://user-images.githubusercontent.com/3784411/36709103-cc402f48-1ba8-11e8-8444-974da7c99fde.png">

On the other hand, when I tried the SDK with a dummy app, it works perfectly, showing the correct stack trace of the JS crash. 
<img width="781" alt="screen shot 2018-02-27 at 10 33 12" src="https://user-images.githubusercontent.com/3784411/36709295-b1f4b338-1ba9-11e8-9771-66231314e33a.png">

The stack trace stops on RCTAssert.m if I forgot to upload the bundle along with the dSYM. 
<img width="979" alt="screen shot 2018-02-27 at 10 36 03" src="https://user-images.githubusercontent.com/3784411/36709359-122163b4-1baa-11e8-83ed-34cfc813fd55.png">

1. What do I need to do to make it work in my app?
2. How do you guys decide when to show JS stack trace instead of native ones?
Assuming that the crash reporter needs to land on RCTAssert.m for it to work properly, I have additional information that might help. When using Crashlytics, the crash report lands correctly on RCTAssert.m. 
I've also uninstalled Crashlytics to make sure the two crash reporters don't conflict.

**Comment by guperrot** [comment] 2018-02-27 21:39
Hi the first crash is a native C++ crash not caused by a Javascript error, that's why it looks different. The cause is most likely a bug in react-native code for iOS that you should report to facebook.

**Comment by guperrot** [comment] 2018-02-27 21:43
The first crash is not Javascript. Something wrong happened in Facebook native code and their native module threw an objective C exception, not javascript.

Our SDK also handles objective C exceptions and they look different.

**Comment by esam091** [comment] 2018-02-28 00:57
Thanks for replying. Is there anything that I can do to figure out the problem?

**Comment by guperrot** [comment] 2018-02-28 01:00
This is all the information we got, you can probably get the RAW tab details of an individual occurrence and create a bug against React Native repository as they are probably causing the issue.

**Comment by guperrot** [comment] 2018-03-03 03:07
Hey! 

We haven't heard from you in a while, so I am going to go ahead and close this conversation. Should you still have any questions, please don't hesitate to contact us again. 

Thanks for using App Center!

**Comment by mmiani** [comment] 2018-07-04 10:03
I'm having kind of the same issue, I'm not able to see the JS stack trace.
This is the log generated by JS crash caused by:

`throw new Error('This is a test javascript crash!');`

![screen shot 2018-07-04 at 8 00 18 pm](https://user-images.githubusercontent.com/2457743/42270759-fa1c1fd2-7fc4-11e8-8616-80de0e158e4b.png)

**Comment by mattslight** [comment] 2018-11-30 15:32
@guperrot I have the same issue. i do:

```
Crashes.setListener({ shouldProcess: true })
throw Error('test error')
```

And I only see the Objective-C trace. Showing RCTAssert.m line 132.

I also specified send Javascript crashes at react-native link

**Comment by guperrot** [comment] 2018-11-30 20:19
@mmiani @mattslight the SDK does not do anything special regarding symbolication, it all happens on server side with uploaded symbols that contain the source map. If you already made sure you uploaded symbols containing the javascript source map as documented in https://docs.microsoft.com/en-us/appcenter/diagnostics/symbolication#uploading-symbols and it's not working for you, then please open a support ticket from any page of https://appcenter.ms and describe the problem, preferably download the json report file from a single occurrence of the crash and share it with support engineers there.

Also shouldProcess is a function, not a property, the default if undefined is already a function that returns true so you don't need the listener at all in your case.

**Comment by harrisonschwartz** [comment] 2019-10-08 03:00
Somehow our app ended up in this state as well. I believe it happened after updating to RN 59.10

**Comment by Jamminroot** [comment] 2019-10-08 11:32
@harrisonschwartz can you check whether updating RN version fixes the problem? As per @guperrot's [comment](https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/248/#issuecomment-443327272) it looks like RN problem, and not SDK.

**Comment by sarmad1995** [comment] 2019-10-29 07:25
Same issue, can't see what is the real problem here.
I am also using codepush with my app, maybe that must have some issue?

**Comment by annakocheshkova** [comment] 2019-10-29 08:45
@sarmad1995 I don't think it should. Have you managed to try the suggestions above?

**Comment by caisd1998** [comment] 2019-12-25 11:39
Same problem. I think this feature is down for new version of react native.
I created a react native app with initial template (version 0.60.5), and then add two buttons to trigger javascript and native crashes according to [this document in appcenter](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/react-native#generate-a-test-crash).
I then used appcenter to build this app to iOS app, both javascript and native crashes are reported correctly with native stack trace, while javascript crash's javascript stack trace didn't show the line.
I'm contacting support to take a look.

**Comment by russelarms** [comment] 2019-12-25 16:03
@caisd1998 have you uploaded **index.ios.map** file in the same .zip file according to [this paragraph](https://docs.microsoft.com/en-us/appcenter/diagnostics/ios-symbolication#react-native-ios-apps)?

**Comment by caisd1998** [comment] 2019-12-26 02:17
@russelarms There is no need to upload source map or symbol files, because I'm building within appcenter, it has been taken care of, see the top part of the document you mentioned:

> The App Center Build and Distribution service can automatically generate a valid dSYM and source map .zip file and upload the file to the Diagnostics service. If you use App Center to build and auto distribute your app to your end users, you don't need to manually obtain and upload the symbol files as detailed in the steps below.

**Comment by caisd1998** [comment] 2019-12-26 05:55
This is the reported crash:
<img width="1222" alt="Screen Shot 2019-12-26 at 13 52 29" src="https://user-images.githubusercontent.com/14158488/71460509-20d54d80-27e7-11ea-84bb-fd33f689ce38.png">

This is the [source code](https://github.com/caisd1998/test-react-native-crash/blob/master/App.tsx).

**Comment by victorkvarghese** [comment] 2020-01-29 04:49
Anyone found a solution?? I'm facing the same issue. I'm using appcenter to build and deploy the app

**Comment by caisd1998** [comment] 2020-01-29 11:04
> Anyone found a solution?? I'm facing the same issue. I'm using appcenter to build and deploy the app

There's nothing we can do. I've contacted with App Center support, and he confirmed this issue, just that is tracked as an internal bug, don't know when this can be fixed...

**Comment by MrTact** [comment] 2020-02-05 00:04
I spent a bit of time on this recently as it is affecting my team as well. The most interesting and perhaps useful piece of information was that crashes inside the render loop seem to get their JS stack trace uploaded successfully. Crashes in response to e.g. an event handler callback (outside the render loop) **do** create a JS stack trace in the .plcrash file, which is textually subtly different than the render loop crash, but the JS portion of the crash dump (appended to "additional info") doesn't show up after it is uploaded. I haven't been able to figure out why; inspecting the structure of the exception that gets thrown by each of these cases doesn't show any discernable difference, and for obvious reasons it's really hard to debug the actual crash dump part of the process.

**Comment by MrTact** [comment] 2020-02-05 00:05
Should also probably mention https://github.com/microsoft/appcenter/issues/857 might be related.

**Comment by caisd1998** [comment] 2020-02-05 14:24
Here is the response from app center support:

Minor update here: the work item is being reviewed and finalized.
You can track this with those PRs:
https://github.com/microsoft/appcenter-sdk-apple/pull/1959
https://github.com/microsoft/appcenter-sdk-react-native/pull/798
Once those merged, the next release (the one after the merge) should contain fix for your problem.

**Comment by victorkvarghese** [comment] 2020-02-19 06:38
Did these commits helped anyone? I'm still not able to get JS lines in stacktrace.
I even created a new app and tried..

**Comment by MatkovIvan** [comment] 2020-02-19 11:53
@victorkvarghese The fix isn't released yet, it will be included to the next version

**Comment by victorkvarghese** [comment] 2020-02-19 12:40
Hi,

We are working of figuring out why stack trace is not working for js for
over 2 months now..when can we expect a release ?

**Comment by MatkovIvan** [comment] 2020-02-19 12:46
Before the end of this month, most likely in the next couple of days.

**Comment by patman1** [comment] 2020-02-19 16:58
Is this iOS specific? I'm experiencing the same issue on React Native Android.

**Comment by russelarms** [comment] 2020-02-20 08:46
@patman1, unfortunately, we don't have support for JS stack traces it on Android yet.
You can track and vote here to support the feature request: https://github.com/microsoft/appcenter/issues/75

**Comment by patman1** [comment] 2020-02-20 08:57
This unbelievable feature gap deserves at least mention in official setup docs
https://docs.microsoft.com/en-us/appcenter/sdk/crashes/react-native it would save some time.

**Comment by guperrot** [comment] 2020-02-24 19:25
The new version of the SDK has been released with a fix: [3.0.0](https://github.com/microsoft/appcenter-sdk-react-native/releases/tag/3.0.0).

**Comment by guperrot** [comment] 2020-02-24 19:27
This is the related entry in core module that was responsible for this bug (it was not a bug in crashes module itself): 

> **[Fix]** Fix an issue where React Native SDK would not send wrapperSdk information.

**Comment by victorkvarghese** [comment] 2020-02-25 15:54
Please reopen this thread..
Updated to 3.0.0, Disabled bitcode, Symbols are uploaded automatically via appcenter. 

Still the same issue. I'm in contact with appcenter team for almost one month now..

![Screenshot 2020-02-25 at 9 23 54 PM](https://user-images.githubusercontent.com/15869386/75264247-26fe9f00-5815-11ea-94c3-7f2a8871c65d.png)

**Comment by Jamminroot** [comment] 2020-02-25 17:05
@victorkvarghese can that be reproduced on new, fresh project, or is it only after update?

**Comment by victorkvarghese** [comment] 2020-02-26 05:01
@Jamminroot i was having these issue on old version and the latest ones as well

**Comment by Jamminroot** [comment] 2020-02-26 06:52
@victorkvarghese ok, and can it be reproduced on clean project? When you just create new project, add SDK, and try running few pieces of code? Or does it only occur after update to newer version?

**Comment by Jamminroot** [comment] 2020-02-26 08:40
Also, have you, by any chance, ran `react-native bundle --entry-file index.ios.js --platform ios --dev false --reset-cache --bundle-output unused.jsbundle --sourcemap-output index.ios.map` as per [documentation](https://docs.microsoft.com/en-us/appcenter/diagnostics/iOS-symbolication#uploading-symbols)?

**Comment by victorkvarghese** [comment] 2020-02-27 05:56
@Jamminroot  I diged deep to crash reports the` sdkVersion: 2.5.3`  not` 3.0.0`.
I did upgrade the app by replacing versions in package.json and re running pod install.

But not sure why sdkversions are still` 2.5.3` in crash reports.

**Comment by russelarms** [comment] 2020-02-27 06:23
@victorkvarghese 

> I did upgrade the app by replacing versions in package.json and re-running pod install.

Have you run `npm i` or `yarn install` after that?

You can also try to run `pod install --repo-update` instead of `pod install`.

**Comment by victorkvarghese** [comment] 2020-02-27 06:42
@russelarms We tried that as well, same thing
```
 - appcenter-core (3.0.0):
     - AppCenterReactNativeShared
     - React
   - AppCenter/Core (2.5.3)
   - AppCenterReactNativeShared (2.6.1):
     - AppCenter/Core (= 2.5.3)
```

**Comment by victorkvarghese** [comment] 2020-02-27 07:35
@russelarms Thnaks its worked. Able to update to 3.0.0

@Jamminroot Updating to latest version solved the issue for me. You can close the issue now.

Thanks a lot guys..

**Comment by victorkvarghese** [comment] 2020-02-27 08:33
![Screenshot (18)](https://user-images.githubusercontent.com/15869386/75426107-f54b1c80-5969-11ea-8441-939ced879cd7.png)

**Comment by Jamminroot** [comment] 2020-02-27 09:16
Glad it worked.
Have a nice day!

**Closed by Jamminroot** 2020-02-27 09:16 UTC
Labels: bug

**Comment by glacjay** [comment] 2022-06-15 04:20
There is another hint: DON'T add `--minify false` to your `react-native` command, as it will break appcenter's parsing of JS stacetrace.

It had bothered me for a looooong time. Hope it's helpful to someone.
