### ISSUE TITLE
Use of undeclared identifier 'customProperties'

### ISSUE THREAD

**Issue by AmirDoreh** [microsoft/appcenter-sdk-react-native#961] opened 2022-02-06 14:55 UTC
### **Description**

from today i started getting this error.
<img width="1409" alt="Screen Shot 2022-02-06 at 5 53 04 PM" src="https://user-images.githubusercontent.com/45465967/152686734-a3150654-2b18-4f88-9501-8406ad862950.png">

### **Details**
```

System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 27.25 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 17.0.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 2021.11.08.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      Android NDK: 23.0.7272597-beta3
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

```
"appcenter": "4.3.0",
"appcenter-analytics": "4.3.0",
"appcenter-crashes": "4.3.0",

```

**Comment by AnatolyPristensky** [comment] 2022-02-07 11:18
Hello, @DeebanT2S !
Thanks for getting in touch with us!
`AppCenter.setCustomProperties` API has been removed in the new version of SDK. 
At first glance It looks like a duplicate of #955.

Please, make sure that you updating to the latest App Center SDK version (4.4.3) correctly and try to perform:

- pod cache clean --all
- pod repo update

Also, please make sure that Podfile.lock file is updated. Try to remove it, run pod install, and check if the issue is gone.

**Closed** 2022-02-07 11:19 UTC
Labels: support
