### ISSUE TITLE
AppCenter build for React Native iOS is throwing errors

### ISSUE THREAD

**Issue by sikyuny-hrbl** [microsoft/appcenter-sdk-react-native#956] opened 2022-01-25 18:22 UTC
### **Description**
AppCenter build for React Native iOS is throwing errors since yesterday

### **Repro Steps**

Have tried multiple versions such as 4.x.x and all failed with following logs

### **Details**
7.  Include the logs here:

/Users/runner/work/1/s/node_modules/appcenter/ios/AppCenterReactNative/AppCenterReactNative.m:97:5: error: use of undeclared identifier 'MSACCustomProperties'
    MSACCustomProperties *customProperties = [MSACCustomProperties new];
    ^
/Users/runner/work/1/s/node_modules/appcenter/ios/AppCenterReactNative/AppCenterReactNative.m:97:27: error: use of undeclared identifier 'customProperties'
    MSACCustomProperties *customProperties = [MSACCustomProperties new];
                          ^
/Users/runner/work/1/s/node_modules/appcenter/ios/AppCenterReactNative/AppCenterReactNative.m:97:47: error: use of undeclared identifier 'MSACCustomProperties'
    MSACCustomProperties *customProperties = [MSACCustomProperties new];
                                              ^
/Users/runner/work/1/s/node_modules/appcenter/ios/AppCenterReactNative/AppCenterReactNative.m:107:22: error: use of undeclared identifier 'customProperties'
                    [customProperties setString:value forKey:key];
                     ^
/Users/runner/work/1/s/node_modules/appcenter/ios/AppCenterReactNative/AppCenterReactNative.m:110:22: error: use of undeclared identifier 'customProperties'
                    [customProperties setNumber:value forKey:key];
                     ^
/Users/runner/work/1/s/node_modules/appcenter/ios/AppCenterReactNative/AppCenterReactNative.m:114:22: error: use of undeclared identifier 'customProperties'
                    [customProperties setBool:[num boolValue] forKey:key];
                     ^
/Users/runner/work/1/s/node_modules/appcenter/ios/AppCenterReactNative/AppCenterReactNative.m:118:22: error: use of undeclared identifier 'customProperties'
                    [customProperties setDate:date forKey:key];
                     ^
/Users/runner/work/1/s/node_modules/appcenter/ios/AppCenterReactNative/AppCenterReactNative.m:121:22: error: use of undeclared identifier 'customProperties'
                    [customProperties clearPropertyForKey:key];
                     ^
/Users/runner/work/1/s/node_modules/appcenter/ios/AppCenterReactNative/AppCenterReactNative.m:126:20: error: no known class method for selector 'setCustomProperties:'
    [MSACAppCenter setCustomProperties:customProperties];
                   ^~~~~~~~~~~~~~~~~~~
/Users/runner/work/1/s/node_modules/appcenter/ios/AppCenterReactNative/AppCenterReactNative.m:126:40: error: use of undeclared identifier 'customProperties'
    [MSACAppCenter setCustomProperties:customProperties];
                                       ^
/Users/runner/work/1/s/node_modules/appcenter/ios/AppCenterReactNative/AppCenterReactNative.m:126:20: error: no known class method for selector 'setCustomProperties:'
    [MSACAppCenter setCustomProperties:customProperties];
                   ^~~~~~~~~~~~~~~~~~~
11 errors generated.

**Comment by kale1d** [comment] 2022-01-25 20:02
same issue here

**Comment by alihassan0** [comment] 2022-01-25 21:13
Facing a similar problem today.
  [MSACAnalytics startSession];

**Comment by AnastasiaKubova** [comment] 2022-01-26 06:09
Hi there! Thanks for getting in touch with us!
Looks like this is a duplicate of #955.

Please make sure that you use the latest App Center SDK version ([4.4.3](https://github.com/microsoft/appcenter-sdk-react-native/releases/tag/4.4.3)) and try to perform:
- `pod cache clean --all`
- `pod repo update`

**Comment by bernard-kms** [comment] 2022-01-26 08:01
It's also good to make sure the `Podfile.lock` entries are pointing correctly to the installed version, e.g. `- appcenter-analytics (4.3.0):` for the latest SDK version.

**Comment by TomCorvus** [comment] 2022-01-26 09:40
Same issue as @alihassan0 with `No known class method for selector 'startSession'` error.
I cleaned pod cache and update pods but it doesn't work. (cc @AnastasiaKubova)
Versions in `Podfile.lock` seems to be good:
```
- appcenter-analytics (4.4.3):
    - AppCenter/Analytics (~> 4.0)
    - AppCenterReactNativeShared (~> 4.0)
    - React-Core
  - appcenter-core (4.4.3):
    - AppCenterReactNativeShared (~> 4.0)
    - React-Core
  - appcenter-crashes (4.4.3):
    - AppCenter/Crashes (~> 4.0)
    - AppCenterReactNativeShared (~> 4.0)
    - React-Core
  - AppCenter/Analytics (4.3.0):
    - AppCenter/Core
  - AppCenter/Core (4.3.0)
  - AppCenter/Crashes (4.3.0):
    - AppCenter/Core
  - AppCenterReactNativeShared (4.3.0):
    - AppCenter/Core (= 4.3.0)
 ```

No problem with `4.3.0` version.

**Comment by AnatolyPristensky** [comment] 2022-01-26 09:54
Hello @TomCorvus ,
Please make sure that Podfile.lock file is updated. Try to remove it and run pod install.
Your Podfile.lock should look like:

```
 - AppCenter/Analytics (4.4.1):
    - AppCenter/Core
  - AppCenter/Core (4.4.1)
  - AppCenter/Crashes (4.4.1):
    - AppCenter/Core
  - AppCenterReactNativeShared (4.4.3):
    - AppCenter/Core (= 4.4.1)
```

**Comment by TomCorvus** [comment] 2022-01-26 10:23
Thanks @AnatolyPristensky, I had to remove `Podfile.lock` as you advised me, and it is now up-to-date with `pod install`

**Closed** 2022-01-26 10:48 UTC
Labels: support

**Comment by chenop** [comment] 2022-02-17 13:16
Something is wrong with 4.4.3
Getting: 
`.../node_modules/appcenter-analytics/ios/AppCenterReactNativeAnalytics/AppCenterReactNativeAnalytics.m:69:18: no known class method for selector 'startSession'
`

Resolved that by:
- Downgrading to 4.3.0 in package.json
- pod cache clean --all
- pod install

**Comment by AnatolyPristensky** [comment] 2022-02-18 06:54
Hello, @chenop 
Please, make sure that you updating to the latest App Center SDK version (4.4.3) correctly and try to perform:

- pod cache clean --all
- pod repo update

Also, please make sure that Podfile.lock file is updated. Try to remove it, run pod install, and check if the issue is gone.
