### ISSUE TITLE
carthage support

### ISSUE THREAD

**Issue by pvinis** [microsoft/appcenter-sdk-react-native#31] opened 2017-05-08 10:03 UTC
i hate hate hate cocoapods, and many other people do.
could you please add carthage support?
also some better instructions on how to add the react native sdk manually.
thanks.

**Comment by TroubleMakerBen** [comment] 2017-05-08 16:48
Hey @pvinis,

Thanks for getting in touch. We have Carthage support on our roadmap, but I cannot give you an ETA just now.
Please bear with us, we are really hard at work and take your input seriously!

Best,
Benny

**Comment by pvinis** [comment] 2017-05-08 17:12
hi benny. thanks for the reply. I just made the issue because I didn't see it anywhere and thought it's important.

thank you for doing it, and for developing this in general. all react native crash reporting tools are kind of a mess, and your looks promising.
I will keep an eye out in the repo in case I can help, as I will be using this already. (with cocoapods which I hate, but still 😛).

now you just need to have a way to upload the symbols and sourcemaps to media center using a script, and then I can fully switch to you 😁

**Comment by TroubleMakerBen** [comment] 2017-05-08 22:47
Hey Pavlos,
Thanks for the encouragement.
I (and also the rest of our team) is kinda "guilty" of the mess, too, as it was more of an afterthought for HockeyApp because it started with iOS and macOS and then "spread" to other platforms , and Mobile Center is different in that we take all platforms into account from the start.

I'll forward the feedback about carthage and the scripts to the involved PMs so they know about you. ;)
Talking about scripting symbol upload. Are you aware of our [CLI](https://github.com/Microsoft/mobile-center-cli)? It allows symbol upload.

Cheers!
Benny

**Comment by pvinis** [comment] 2017-05-09 07:56
o nice. didnt know about the cli tool. i tried it now, and it uploaded, so now i will try to generate some crashes and check.

**Comment by TroubleMakerBen** [comment] 2017-05-09 16:14
Let me know if this works. Also let me know if something doesn't work, so I can ping the right people.
If you have any other complaints, feedback, advice,... don't hesitate to get in touch!

Benny

**Comment by max-horvath** [comment] 2017-11-18 17:26
Hi, given the request is a few months old - how is the progress on Carthage support?

Thanks,
Max

**Comment by idStar** [comment] 2018-03-05 14:13
I'm waiting for Carthage support too. I've been holding off on adopting App Center for this reason. I don't like pulling in a kitchen sink of complexity the Cocoapods brings, relative to the clean simplicity of Carthage.

**Comment by jamesone** [comment] 2018-03-20 23:06
Are you sure they don't already support it? https://docs.microsoft.com/en-us/appcenter/general/changelog#july-2017

**Comment by idStar** [comment] 2018-03-20 23:08
The building of apps that pull in other dependencies via Carthage works fine. I've since built that way. I was speaking of the AppCenter framework itself. I didn't see support in the readme, so I just integrated it manually.

**Comment by jamesone** [comment] 2018-03-20 23:11
Oh okay, Cool! So if I were to setup my app using app center, it would be able to detect the Cartfile, install the dependencies, and give me a installable build?

**Comment by idStar** [comment] 2018-03-20 23:12
Yes @jamesone. I've confirmed that myself with some builds last month. So jump in. The water is fine!

**Comment by jamesone** [comment] 2018-03-20 23:23
Nice! So pretty much IF you want to use track Analytics, Record crashes, and use the Push notifications feature, you need to set it up manually OR with cocoapods right? (https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native)

Other than that, using carthage is fine to build your app?

Sounds good! Hopefully they implement Carthage for the RN-SDK soon 👍

**Comment by idStar** [comment] 2018-03-20 23:25
Yes, that's my take, although I'm using straight iOS (not the react-native approach).

**Comment by nboyd-sportdx** [comment] 2018-05-17 12:07
@idStar you integrated it manually.   where did you get the source files?  i too have been frustrated with cocoapods and refuse to use it

**Comment by idStar** [comment] 2018-05-17 13:01
It's been a while. I went through the installation instructions and there was a link there, or perhaps it was the releases tab here on GitHub.

**Comment by DmitriyKirakosyan** [comment] 2021-12-03 14:19
Hi guys, it seems that react-native doesn't officially support Carthage yet, see https://github.com/facebook/react-native/issues/13835.

**Comment by DmitriyKirakosyan** [comment] 2024-04-15 04:33
As we do not have plans to add support for this feature in the next year, I'm closing the issue.

**Closed by DmitriyKirakosyan** 2024-04-15 04:33 UTC
Labels: feature request
