### ISSUE TITLE
'AppCenterReactNativeShared/AppCenterReactNativeShared.h' file not found

### ISSUE THREAD

**Issue by computerjazz** [microsoft/appcenter-sdk-react-native#765] opened 2019-11-05 19:50 UTC
### **Description**

`'AppCenterReactNativeShared/AppCenterReactNativeShared.h' file not found` in `AppDelegate.m`

### **Repro Steps**

1. Follow installation steps here: https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native
2. Build app

### **Details**

I noticed the example app references a local file: https://github.com/microsoft/appcenter-sdk-react-native/blob/develop/TestApp/ios/Podfile#L38
I'm not sure what is in AppCenterReactNativeShared -- is it necessary?

1. Which version of the App Center SDK are you using?
    - e.g. 2.5.0

Place output here

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

1.8.4

**Comment by guperrot** [comment] 2019-11-05 20:11
Hi, TestApp is a special app that uses project references and not the published npms.
A better example is DemoApp, the one using npms.

What react native SDK version are you using?
We also have a known issue with Cocoapods 1.8.4, in #760 we recommend downgrading to 1.7.5 while we are investigating.

**Comment by computerjazz** [comment] 2019-11-05 20:15
Hm, DemoApp is on React Native 59, so autolinking wouldn't come into play, as described here: https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#31-integrate-the-sdk-automatically-for-react-native-060

I have tried both pods versions.

Do I need to import `AppCenterReactNativeShared` in `AppDelegate.m` at all?

**Comment by guperrot** [comment] 2019-11-05 21:41
You don't need to include `AppCenterReactNativeShared/AppCenterReactNativeShared.h`, our test app uses it for internal overriding but it's an advanced undocumented scenario. Does your app build by just removing this import? We will update the documentation after you confirm.

**Comment by computerjazz** [comment] 2019-11-05 21:46
Well, it doesn't build yet, but removing it at least gets me past that particular error. Now I'm getting `Symbol(s) not found for architecture x86_64` errors at the linking stage, but that's a separate issue :).

Thanks!

**Comment by guperrot** [comment] 2019-11-05 21:47
Are the missing symbols from our SDK or should I close this?

**Comment by computerjazz** [comment] 2019-11-05 21:49
Some are. But I'm thinking I should open a separate issue?
![Screen Shot 2019-11-05 at 1 49 02 PM](https://user-images.githubusercontent.com/6730148/68249174-18c11480-ffd3-11e9-929b-57f95ae7ebbc.png)

**Comment by guperrot** [comment] 2019-11-05 21:56
You can just rename the title at this point.

Just to be sure, you are opening `xcworkspace` in XCode and not the `xcodeproj` (only xcworkspace will work)?
Do you see the Pods in XCode with all the AppCenter frameworks underneath?
If yes to the 2 questions above is framework search path including everything?

<img width="873" alt="Screen Shot 2019-11-05 at 12 05 15 PM" src="https://user-images.githubusercontent.com/623672/68249623-07c4d300-ffd4-11e9-8af2-1f5d6825e3c2.png">

You seem to have issues with Bugsnag as well (by the way on iOS you cannot have 2 crash reporter libs active at the same time).

**Comment by computerjazz** [comment] 2019-11-06 00:48
Aha! My bad, I am upgrading from RN 59 and failed to add `use_native_modules!` to my `Podfile`, so autolinking wasn't working at all!

Thanks for your help!
btw it looks like autolinked pods go in `Pods/Development Pods/appcenter`
![Screen Shot 2019-11-05 at 2 46 11 PM](https://user-images.githubusercontent.com/6730148/68252749-28445b80-ffdb-11e9-8181-17cb44defa9a.png)

**Comment by guperrot** [comment] 2019-11-06 00:58
Glad your issue was solved and thanks for using App Center.

**Closed by guperrot** 2019-11-06 00:58 UTC
Labels: support

**Comment by dragoalexa97** [comment] 2020-10-02 07:28
I am getting this error on Xcode12. cocoapods version is 1.9.3

**Comment by annakocheshkova** [comment] 2020-10-05 10:09
Hi there @dragoalexa97! I couldn't reproduce your issue on XCode 12.2 beta 2 + cocoapods 1.9.3.
Could you open a separate ticket and provide some logs? Thank you.
