### ISSUE TITLE
Crashes not appearing in AppCenter

### ISSUE THREAD

**Issue by mmiani** [Microsoft/AppCenter-SDK-React-Native#349] opened 2018-07-11 23:04 UTC
### **Description**
 I'm sniffing the requests to AppCenter after a crash, it sends the crash stack trace and the error attachment correctly, but for some reason, I can't see the reports in AppCenter.
I'm not pretty sure, but I suspect it started happening since I send the index.ios.map with the symbols 

![image](https://user-images.githubusercontent.com/2457743/42603036-74de35ee-85af-11e8-9bcf-f770c1930489.png)

![image](https://user-images.githubusercontent.com/2457743/42603044-7e203044-85af-11e8-933f-acb4a9386cdc.png)

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Generate a JS crash
2. Open the app again

### **Details**

1. Which SDK version are you using?
    - 1.6.0
2. Which OS version did you experience the issue on?
    - iOS 11.4
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone 7 Plus physical device
    - iPhone 6 emulator
    - iPhone 8
4. What third party libraries are you using?
    N/A
5. Run the following command and paste the output below: `react-native info`
Environment:
  Node: 6.11.1
  npm: 6.1.0
  Watchman: 4.7.0
  Xcode: Xcode 9.3.1 Build version 9E501

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ^0.55.4 => 0.55.4

6. If you're developing for React Native iOS, run the following command and paste the output below: 
   1.3.1

[logs - stack trace.txt](https://github.com/Microsoft/AppCenter-SDK-React-Native/files/2186457/logs.-.stack.trace.txt)

[index.ios.map.zip](https://github.com/Microsoft/AppCenter-SDK-React-Native/files/2186484/index.ios.map.zip)

**Comment by TroubleMakerBen** [comment] 2018-07-12 00:39
hey @mmiani,

Just to make sure I understand correctly.

> I'm not pretty sure, but I suspect it started happening since I send the index.ios.map with the symbols

Are you saying that you were able to see crashes in the App Center portal before but since you uploaded the `index.ios.map` you don't?

Just to make sure, have uploaded the symbols and you also read https://docs.microsoft.com/en-us/appcenter/crashes/react-native#uploading-symbols?

**Comment by mmiani** [comment] 2018-07-12 02:34
> Are you saying that you were able to see crashes in the App Center portal before but since you >uploaded the index.ios.map you don't?

yes, as I'm not using the AppCenter build, I need to upload the symbols and the ios map, I'm using the appcenter fastlane plugin to release and upload the symbols.

Before uploading the ios map I was able to see crashes but no the js stack trace, at that point I've realized the fastlane plugins sends the symbols automatically but not the ios.map so I've started adding the index.ios.map in the symbols package. After that, the crashes are not visible anymore.

I can see the symbols being uploaded to AppCenter (the dsym file and the index.ios.map) and the requests to log the crashes being sent as well

**Comment by TroubleMakerBen** [comment] 2018-07-19 04:45
Hey @mmiani,

we're still looking into this. 
Would you mind sharing the structure of the `zip`-file that includes the dsym and the `index.ios.map` that you are uploading using the appcenter fastlane plugin?

**Comment by TroubleMakerBen** [comment] 2018-07-19 18:22
Hey @mmiani,

I just wrapped up testing and I cannot reproduce the issue that you are seeing. My `dSYM.zip` contains the symbol file and the `index.ios.map` in the same folder.
Have you checked the tab that shows unsymbolicated crashes? Crashes without symbols won't show up and if you provide symbols later, only new crashes will be symbolicated.

**Comment by mmiani** [comment] 2018-07-20 05:51
Here you have the zip files that include the dsym and the `index.ios.map`
[upload-2018-07-19T08-01-49Z.zip](https://github.com/Microsoft/AppCenter-SDK-React-Native/files/2212606/upload-2018-07-19T08-01-49Z.zip)
I don't have unsymbolicated crashes.
Anyway, I've received the following messages from the AppCenter portal support:

>Okay, I checked our logs. Just to confirm: this is not an issue on your end. We are receiving your crash log and saving it on our end. The issue we're having is that we aren't processing it properly after that.

>The fix for this is on the way. Hope that this sorts your issue.

So I assume they are taking care of the issue

**Comment by TroubleMakerBen** [comment] 2018-07-20 19:06
Hey @mmiani,

thx for the zip file that looks good. I had a chat with the backend folks and they deployed the fix for the processing on 2018-7-12:26, so all should be well. 

Thank you so much for the patience and the help in tracking this down and we will make sure we improve the response time for future cases.

I'm also closing this issue but please get in touch any time (feel free to reopen this issue if necessary).

**Closed by TroubleMakerBen** 2018-07-20 19:06 UTC
Labels: support
