### ISSUE TITLE
ld: library not found for -lPods-AppName

### ISSUE THREAD

**Issue by divyamakkar26** [Microsoft/AppCenter-SDK-React-Native#456] opened 2018-10-30 10:12 UTC
Am uisng the following versions of app center :

 "appcenter": "^1.8.1",
 "appcenter-analytics": "^1.8.1",
 "appcenter-crashes": "^1.8.1",

ld: library not found for -lPods-AppName
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please help in solving this issue.I am not sure whether this is related to app center or not.
Thanks in advance.

**Comment by dhei** [comment] 2018-10-31 01:54
Hi @divyamakkar26,

Thanks for getting in touch.

Error `clang: error: linker command failed with exit code 1 (use -v to see invocation)` looks like a SDK integration error, please follow our [React Native get-started documentation](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#3-add-the-app-center-sdk-modules) for step-by-step instructions. 

Once you are able to build locally, make sure you checkin dependencies under `{root}/Pods` into source control so that it works for your CI build.

Btw, I noticed you are using caret(`^`) before version number "1.8.1". We recommend pinning App Center RN SDK version in package.json to avoid issue mentioned in https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/449. This is not related to your current clang error, but it may be worth mentioning. For instance:
```
"appcenter": "1.8.1",
"appcenter-analytics": "1.8.1",
"appcenter-crashes": "1.8.1",
```

**Comment by divyamakkar26** [comment] 2018-10-31 02:05
Hi @dhei 

Am able to build locally with my current setup but not able to build with app center.

**Comment by dhei** [comment] 2018-10-31 02:15
@divyamakkar26 If it works locally but not on App Center Build, it may be caused by not checking in your Pods dependencies to Git. 

We use this repo to provide support primarily for App Center RN SDK. For App Center Build related issues, I recommend open an intercom ticket using the blue chat button on appcenter.ms portal. I am closing this issue for now. Please feel free to contact us if you have more questions.

Thanks.

**Closed by dhei** 2018-10-31 02:15 UTC
Labels: support

**Comment by divyamakkar26** [comment] 2018-10-31 02:18
Thanks for your help @dhei.

**Comment by nicholascm90** [comment] 2019-03-05 22:14
@divyamakkar26 Were you able to resolve this ? I have the same error only on appcenter builds. My Pods are already being checked in to source control.

**Comment by nicholascm90** [comment] 2019-03-06 12:59
FYI for anyone who stumbles onto this thread: I was able to resolve this issue by opening the build configuration, and choosing "Save and Build". This forces appcenter to check for .xcodeworkspace again. It was previously building a project file instead
