### ISSUE TITLE
Lexical or preprocessor issue group in  React Native + AppCenter/MSAppCenter.h' file not found

### ISSUE THREAD

**Issue by prorohit** [microsoft/appcenter-sdk-react-native#892] opened 2021-01-20 10:48 UTC
Hi Appcenter team,

I am getting the error while using Xcode 11.4.1 in the integration of Appcenter SDK in React Native Project

AppCenter/MSAppCenter.h' file not found

React Native Info:
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 602.35 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: ^0.61.5 => 0.61.5

Cocoa Pods Info:
1.8.3

**Steps Followed to resolved the issue:**

1. Deleted node_modules folder 
2. Integrated yarn install again
3. Re-Installed the pods 
4. Clean Xcode Build
5. Delete Derived Data

Note: This was working and suddenly stopped working today.

#
<img width="1398" alt="Screen Shot 2021-01-20 at 2 45 47 PM" src="https://user-images.githubusercontent.com/25680719/105164230-505fa200-5b2e-11eb-96b2-dd7c00a04a25.png">

**Comment by lnmunhoz** [comment] 2021-01-21 03:52
I've been struggling with the same issue for the last 3 days. If I update appcenter packages to v4 I can't build my iOS app.

**Comment by AnastasiaKubova** [comment] 2021-01-25 07:42
Hi! Thanks for getting in touch with us! 
This can be related to the cache issue or with incorrect installing App Center dependencies.
Could you please try to:
- Close Xcode and stop node bundler if running
- Reinstall App Center dependencies (remove and add them again)
- Perform `react-native link`
- Reopen Xcode
- Clean and rebuild your project.

I am closing this issue as a [duplicate](https://github.com/microsoft/appcenter-sdk-react-native/issues/347).

**Closed by AnastasiaKubova** 2021-01-25 07:42 UTC

**Comment by jarvisluong** [comment] 2021-02-03 11:54
@AnastasiaKubova Hey, the issue is not actually a duplicate. As you can see this is related to the newest version of Appcenter ios sdk. We have both tried on a clean install and the build error still persist.

**Comment by MatkovIvan** [comment] 2021-02-03 15:31
Hi there,

I see that you're using old CocoaPods version. I guess that's the problem in your case.
> Cocoa Pods Info:
> 1.8.3

From latest version changelog:
> **[Feature]** Use XCFramework format for the binary distribution via CocoaPods. CocoaPods version 1.10+ is a requirement now.

We probably had to increase minor version instead of patch, sorry for that. But anyway, please update CocoaPods to consume the latest version of SDK. Thanks.
