### ISSUE TITLE
Crash in MSACCrashes

### ISSUE THREAD

**Issue by maxsonm** [microsoft/appcenter-sdk-react-native#988] opened 2022-07-18 17:35 UTC
### **Description**

In App Center we are getting crash logs for `MSACCrashes.channel:didPrepareLog:internalId:flags: new:320`

### **Repro Steps**

Have not been able to reproduce locally, but the logs look like it is on app launch.

### **Details**

1. Which version of the App Center SDK are you using?
    4.4.4
2. Which OS version did you experience the issue on?
    iOS 15.0.1, 15.1, 15.2, 15.3.1
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    Physical iPhone XR, iPhone 8, iPhone 11
4. What third party libraries are you using?
    - example
5. Run the following command and paste the output below: `react-native info`
  Binaries:
    Node: 14.19.0 - ~/.asdf/installs/nodejs/14.19.0/bin/node
    Yarn: Not Found
    npm: 6.14.16 - ~/.asdf/installs/nodejs/14.19.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/--/.asdf/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.1 - /usr/local/opt/openjdk/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.4 => 0.67.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`
1.11.3

7. Please enable verbose logging for your app using `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before your call to `[AppCenterReactNative register];` (or any other SDK registration). For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call (you will need to `import com.microsoft.appcenter.AppCenter;`). Include the logs here:

Logs from app center, as we have not been able to reproduce 

```
MSplcrash_signal_handler PLCrashSignalHandler.mm:201
libsystem_platform.dylib _sigtramp
libsystem_pthread.dylib pthread_kill
libsystem_c.dylib abort
libsystem_malloc.dylib malloc_vreport
libsystem_malloc.dylib malloc_report
libsystem_malloc.dylib free
MSACCrashes.channel:didPrepareLog:internalId:flags: new:320
-[MSACChannelGroupDefault enumerateDelegatesForSelector:withBlock:] MSACChannelGroupDefault.m:98
-[MSACChannelGroupDefault channel:didPrepareLog:internalId:flags:] MSACChannelGroupDefault.m:113
-[MSACChannelUnitDefault enumerateDelegatesForSelector:withBlock:] MSACChannelUnitDefault.m:566
-[MSACChannelUnitDefault enqueueItem:flags:] MSACChannelUnitDefault.m:107
-[MSACAnalytics sendLog:flags:] MSACAnalytics.m:0
-[MSACAnalytics trackEvent:withTypedProperties:forTransmissionTarget:flags:] MSACAnalytics.m:359
-[MSACAnalytics trackEvent:withProperties:forTransmissionTarget:flags:] MSACAnalytics.m:310
+[MSACAnalytics trackEvent:withProperties:forTransmissionTarget:flags:] MSACAnalytics.m:238
+[MSACAnalytics trackEvent:withProperties:flags:] MSACAnalytics.m:223
+[MSACAnalytics trackEvent:withProperties:] MSACAnalytics.m:219
-[AppCenterReactNativeAnalytics trackEvent:withProperties:resolver:rejecter:] AppCenterReactNativeAnalytics.m:86
CoreFoundation __invoking___
CoreFoundation -[NSInvocation invoke]
CoreFoundation -[NSInvocation invokeWithTarget:]
-[RCTModuleMethod invokeWithBridge:module:arguments:] RCTModuleMethod.mm:584 facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&, int, (anonymous namespace)::SchedulingContext) RCTNativeModule.mm:183
___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke RCTNativeModule.mm:104
libdispatch.dylib _dispatch_call_block_and_release
libdispatch.dylib _dispatch_client_callout
libdispatch.dylib _dispatch_lane_serial_drain
libdispatch.dylib _dispatch_lane_invoke
libdispatch.dylib _dispatch_workloop_worker_thread
libsystem_pthread.dylib _pthread_wqthread
libsystem_pthread.dylib start_wqthread
```

**Comment by DmitriyKirakosyan** [comment] 2022-07-18 19:09
Hi @maxsonm , thank you for reaching out!

This looks like a duplicate of https://github.com/microsoft/appcenter-sdk-apple/issues/2375.
I'm closing this one, please follow the progress on the issue above.

**Closed by DmitriyKirakosyan** 2022-07-18 19:09 UTC
Labels: support
