### ISSUE TITLE
Update build.gradle to get rid of compile deprecation warnings

### ISSUE THREAD

**Issue by MrLoh** [Microsoft/AppCenter-SDK-React-Native#501] opened 2018-12-22 18:45 UTC
### **Description**

Please update the build.gradle to use `implementation` instead of compile. Currently gradle errors on new RN projects with

```
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
```

This applies to appcenter-analytics and appcenter-crashes as well. It seems like the standalone Android packages of appcenter have already been updated.

### **Details**

1. Which version of the App Center SDK are you using?
    - e.g. 1.11.0
2. Which OS version did you experience the issue on?
    - e.g. Android
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - does not apply
4. What third party libraries are you using?
    - does not apply
5. Run the following command and paste the output below: `react-native info`
```
React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 1.40 GB / 32.00 GB
      Shell: 2.7.1 - /usr/local/bin/fish
    Binaries:
      Node: 10.11.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.57.8 => 0.57.8
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

**Comment by MrLoh** [comment] 2018-12-22 18:58
It seems like @dhei already tried this in 802b5e9b00fdcfdfd801e14a065f6ccfb3fc54f3 and immediately rolled it back in e22c54662d84bc6866328e4bb10ece3975c3bee3 back in July, maybe there still was a compatibility update back then, but most react native libraries have adopted the new syntax now.

**Comment by jaelim-ms** [comment] 2018-12-26 19:35
Hello @MrLoh, Thanks for reporting the issue. We will look at the issue and fix it soon.

**Comment by guperrot** [comment] 2019-01-03 00:42
We have fixed our gradle modules it in our development branch, however it's not released yet.

The fix will work only if also updating to React Native 0.58 (current version of React Native still generates compile includes and is not caused by our SDK) as mentioned in https://github.com/Microsoft/AppCenter-SDK-React-Native/pull/502/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1e.

React Native 0.58 is not yet released as of today (it's a release candidate), as for our SDK you can expect a release end of month.

**Comment by dhei** [comment] 2019-02-12 18:32
As @guperrot mentioned, the issue was fixed in https://github.com/Microsoft/AppCenter-SDK-React-Native/releases/tag/1.12.0. [React Native 0.58.x](https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#0580) was released a while ago, and we confirmed this issue is fixed.

**Closed by dhei** 2019-02-12 18:32 UTC
Labels: bug
