### ISSUE TITLE
Failed to Crash: Possible Unhandled Promise Rejection

### ISSUE THREAD

**Issue by ngandhy** [Microsoft/AppCenter-SDK-React-Native#216] opened 2018-01-09 22:06 UTC
Hi. I tried installing appcenter into my app and upon trying to use Crashes.generateTestCrash() I'm getting the error:

https://www.dropbox.com/s/mq8p2ah5tlo9sij/Screenshot%202018-01-09%2014.05.08.png?dl=0

Would appreciate any help. Thanks!
  

Just installed, so latest versions and followed directions step by step from the logged in appcenter website "add app centers sdk to your app"

**Comment by ngandhy** [comment] 2018-01-09 22:39
btw do you guys have a discord / irc / chat we can join?

**Comment by dhei** [comment] 2018-01-09 22:41
@ngandhy Does your app actually crash when you see this "failed to crash" issue? Do you consistently see this issue when you retry?

Btw - We use intercom for support, just use the blue chat button on any page on appcenter.ms and you can chat with us.

**Comment by ngandhy** [comment] 2018-01-10 02:08
No. It's just a warning. Also nothing shows up in my dashboard :(

**Comment by ngandhy** [comment] 2018-01-10 10:03
I can't tell you why, but I think I figured out a workaround.

The app was upgraded to RN 0.52. But whenever I tried to install AppCenter on this version some wonkiness would ensue. I couldn't get Crashes or Analytics to work. It appears in 0.52 AppCenter installs / links uses CocoaPods which was causing issues. I downgraded to 0.49, installed / linked AppCenter (this time it didn't use CocoaPods) and then upgraded back to 0.52 and everything works now. 

If anyone can explain to me why this is, I'd appreciate the explanation

**Comment by dhei** [comment] 2018-01-11 22:18
Chatted with @ngandhy on intercom support channel. The "Failed to Crash: Possible Unhandled Promise Rejection" error of `Crashes.generateTestCrash()` API is caused by appcenter-crashes module not properly linked into the RN iOS app. 

We still don't fully understand the root cause, but it's likely to be caused by changes of behavior of `react-native link` in react-native v0.51, not really an issue of appcenter sdk.

I will close this issue for now and I can re-open it if more users bump into this issue.

**Closed by dhei** 2018-01-11 22:18 UTC
Labels: support
