### ISSUE TITLE
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.

### ISSUE THREAD

**Issue by dhafagk** [microsoft/appcenter-sdk-react-native#1033] opened 2024-06-28 09:04 UTC
### **Description**

After updating the gradle to 8.1.1, always failed when build.

Execution failed for task ':appcenter-analytics:processDebugManifest'.
> A failure occurred while executing com.android.build.gradle.tasks.ProcessLibraryManifest$ProcessLibWorkAction
   > Incorrect package="com.microsoft.appcenter.reactnative.analytics" found in source AndroidManifest.xml: .../node_modules/appcenter-analytics/android/src/main/AndroidManifest.xml.
     Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.
     Recommendation: remove package="com.microsoft.appcenter.reactnative.analytics" from the source AndroidManifest.xml: .../node_modules/appcenter-analytics/android/src/main/AndroidManifest.xml.

the error happen for Appcenter, Appcenter Analytic, and Appcenter Crashes.

### **Repro Steps**

1. use gradle 8.1.1 and react native 0.72+
2. build using ./gradlew build --warning-mode all

### **Details**

1. Which version of the App Center SDK are you using?
    - v5.0.1
2. Which OS version did you experience the issue on?
    - Android
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - N/A
4. What third party libraries are you using?
    - example
5. Run the following command and paste the output below: `react-native info`

System:
  OS: macOS 14.1.1
  CPU: (8) arm64 Apple M1
  Memory: 111.88 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.9.0
    path: /var/folders/bn/grjdkyvn55q3dg1dfg1r8x7h0000gq/T/yarn--1719565300972-0.6953485893092728/node
  Yarn:
    version: 1.22.19
    path: /var/folders/bn/grjdkyvn55q3dg1dfg1r8x7h0000gq/T/yarn--1719565300972-0.6953485893092728/yarn
  npm:
    version: 10.1.0
    path: ~/.nvm/versions/node/v20.9.0/bin/npm
  Watchman:
    version: 2023.10.30.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK:
    API Levels:
      - "30"
      - "31"
      - "33"
      - "34"
    Build Tools:
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.1
      - 33.0.2
      - 34.0.0
    System Images:
      - android-30 | Google APIs ARM 64 v8a
      - android-30 | Google APIs Intel x86 Atom
      - android-30 | Google APIs Intel x86_64 Atom
      - android-30 | Google Play Intel x86 Atom
      - android-30 | Google Play Intel x86_64 Atom
      - android-33 | Google APIs ARM 64 v8a
      - android-33 | Google APIs Intel x86_64 Atom
      - android-33 | Google Play ARM 64 v8a
      - android-33 | Google Play Intel x86_64 Atom
      - android-34 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10671973
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /Users/dhafagk/.sdkman/candidates/java/current/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: ^18.2.0
  react-native:
    installed: 0.72.7
    wanted: ^0.72.7
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

**Comment by MikhailSuendukov** [comment] 2024-07-04 12:19
Hello, and thank you for reaching out to us. I have prepared a pull request to move the namespace declaration to the build.gradle file.

**Comment by jrobichaud** [comment] 2024-07-18 20:47
@MikhailSuendukov will this fix be available soon? 

There is a deadline for the end of august to make a new builds with Android Target SDK 34. 

Android Target SDK 34 requires gradle 8.1.1.

Thanks.

**Comment by MikhailSuendukov** [comment] 2024-07-23 11:11
@jrobichaud 
The fix has been merged into the develop branch. Could you please test the changes from this [PR](https://github.com/microsoft/appcenter-sdk-react-native/pull/1034) and confirm if the issue is resolved?

**Comment by jrobichaud** [comment] 2024-08-22 13:51
@MikhailSuendukov I started to try to add appcenter from the commit you specified 1 hour ago and I just realized 5.0.2 release appeared about 30 minutes ago in github.

Is 5.0.2 currently being release to npm?

**Comment by jrobichaud** [comment] 2024-08-22 14:06
Ok, I see https://github.com/microsoft/appcenter-sdk-react-native/pull/1041 is currently waiting for review. 🍿

In the meantime I'll continue to try to test it.

**Comment by MikhailSuendukov** [comment] 2024-08-22 14:08
Thank you, yes we are in the process of releasing, please let us know about the results of your testing.

**Comment by jrobichaud** [comment] 2024-08-22 15:11
@MikhailSuendukov

I confirm commit https://github.com/microsoft/appcenter-sdk-react-native/commit/1c9259b671c318f41823938bb359386d5e8c0560 does not prevent me to progress with my target 34 migration anymore but it is as much I can tell for now.

I have to continue to migrate my project and now other libraries prevent me to continue.

I have no idea if it works for now because my app still does not build.

Thanks.

**Comment by lenoirzamboni** [comment] 2024-08-29 18:06
Hello. Getting the same error here. When will the fix be released?

**Comment by MikhailSuendukov** [comment] 2024-09-03 10:19
@lenoirzamboni 
Hello, we are working on the upcoming release. In the meantime, as a temporary solution, you can utilize the current version of appcenter-sdk-react-native available on the develop branch.

**Comment by DordeDimitrijev** [comment] 2024-10-11 13:43
Closing - released with [5.0.2](https://github.com/microsoft/appcenter-sdk-react-native/releases/tag/5.0.2) of SDK

**Closed by DordeDimitrijev** 2024-10-11 13:43 UTC
Labels: next-release
