### ISSUE TITLE
App Center Crashes

### ISSUE THREAD

**Issue by krishna11124** [microsoft/appcenter-sdk-react-native#944] opened 2021-12-08 12:06 UTC
### **Description**

I have integrated this lib in my app so that i am getting its crashes on dashboard but i am not getting these crashes in debug mode Please see that and guide me how can i fixed that.

![Screenshot 2021-12-08 at 5 18 52 PM](https://user-images.githubusercontent.com/61542391/145203598-58827561-3102-4cb6-b00c-04a828234d72.png)

![Screenshot 2021-12-08 at 4 31 55 PM](https://user-images.githubusercontent.com/61542391/145203370-be102a73-30b3-4438-b040-0681d4d1d86f.png)

![Screenshot 2021-12-08 at 4 34 25 PM](https://user-images.githubusercontent.com/61542391/145203525-0e82da6c-d5d1-4c42-baa9-878798599af8.png)

1.Integrates This Lib

### **Details**
**My React Version**:-
"react": "16.9.0",
"react-native": "0.61.5",
**App Center Lib Version**
    "appcenter": "4.2.0",
**Facing issue On This Android Version**
      Android 11,10
**On Device**
      physical device

**Comment by AnastasiaKubova** [comment] 2021-12-08 12:13
Hi! Thanks for getting in touch with us!
Based on your screenshots I don't see that your crash is related to App Center SDK. Could you please share some more detail (reproducing steps and [verbose logs](https://docs.microsoft.com/ru-ru/appcenter/sdk/other-apis/android#adjust-the-log-level))?

**Comment by krishna11124** [comment] 2021-12-08 12:30
Hello i don't have anything like this because this crash is on play store live app and i don't know when and in which code it comes on debug

**Comment by AnastasiaKubova** [comment] 2021-12-08 12:39
Based on your screenshots I don't see any errors related to the App Center. Why do you think that this issue is related to the App Center SDK?

**Comment by krishna11124** [comment] 2021-12-09 04:35
there is no problem with your sdk but after this integration it is produce crash in play store application ..u have any clue for solving out..

**Comment by AnastasiaKubova** [comment] 2021-12-09 06:26
Unfortunately, I don't see any connection between the App Center SDK integration and your crashes. I can advise you to compare your changes with the last two releases and try to identify which changes might break the behavior.
Since this question is not related to the App Center SDK I am closing it but feel free to reopen this issue if you have additional questions or information (reproducing steps and [verbose logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/android#adjust-the-log-level)).

**Closed by AnastasiaKubova** 2021-12-09 06:26 UTC
Labels: support
