### ISSUE TITLE
Notification show as icon in status bar only

### ISSUE THREAD

**Issue by wayne1203** [microsoft/appcenter-sdk-react-native#583] opened 2019-05-27 05:54 UTC
### **Description**

Firebase cloud messaging is work normal. I can receive notification in app (onPushNotificationReceived) or background (icon in status bar only).
I tried add "custom_data" but it's not work to make notification window show.
Also, I search from stackoverflow and said that need to add "setPriority" but it's not such as API in RN Push library.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Using API send request to /push/notifications
2. Receive notification (icon only) in Android

### **Details**

1. Which version of the App Center SDK are you using?
    - 2.0.0
2. Which OS version did you experience the issue on?
    - Android 8.0.0
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Google Pixel emulator
4. What third party libraries are you using?
- "appcenter": "^2.0.0",
- "appcenter-analytics": "^2.0.0",
- "appcenter-crashes": "^2.0.0",
- "appcenter-push": "^2.0.0",
- "axios": "^0.18.0",
- "moment": "^2.24.0",
- "native-base": "^2.12.1",
- "react-native-action-sheet": "^2.2.0",
- "react-native-code-push": "^5.6.0",
- "react-native-device-info": "^2.0.1",
- "react-native-image-crop-picker": "^0.24.1",
- "react-native-router-flux": "^4.0.6",
- "react-native-splash-screen": "^3.2.0",
- "react-native-version-check": "^3.2.1",
- "react-number-format": "^4.0.8",
- "react-redux": "^7.0.3",
- "redux": "^4.0.1"

5. Run the following command and paste the output below: `react-native info`

>   React Native Environment Info:
>     System:
>       OS: macOS High Sierra 10.13.6
>       CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
>       Memory: 31.48 MB / 16.00 GB
>       Shell: 3.2.57 - /bin/bash
>     Binaries:
>       Node: 10.13.0 - /usr/local/bin/node
>       Yarn: 1.12.3 - /usr/local/bin/yarn
>       npm: 6.4.1 - /usr/local/bin/npm
>       Watchman: 4.9.0 - /usr/local/bin/watchman
>     SDKs:
>       iOS SDK:
>         Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
>       Android SDK:
>         API Levels: 22, 23, 26, 27, 28
>         Build Tools: 26.0.2, 27.0.3, 28.0.3
>         System Images: android-18 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom
>     IDEs:
>       Android Studio: 3.4 AI-183.6156.11.34.5522156
>       Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
>     npmPackages:
>       react: 16.8.3 => 16.8.3 
>       react-native: 0.59.8 => 0.59.8 
>     npmGlobalPackages:
>       react-native-cli: 2.0.1

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

Not applied

7. Please enable verbose logging for your app using `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before your call to `[AppCenterReactNative register];` (or any other SDK registration). For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call. Include the logs here:

> 2019-05-27 13:30:28.182 12634-12634/com.testapp D/AppCenterPush: Received push intent=Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x11000010 pkg=com.testapp cmp=com.testapp/com.microsoft.appcenter.push.PushReceiver (has extras) } background=true
>     google.delivered_priority=high
>     google.sent_time=1558935028193
>     google.ttl=2419200
>     google.original_priority=high
>     gcm.notification.e=1
>     gcm.notification.sound=default
>     gcm.notification.title=Title Here
>     from=1020979911088
>     gcm.notification.sound2=default
>     google.message_id=0:1558935028204019%0d963c740d963c74
>     gcm.notification.body=Oh. You got it!!
>     google.c.a.e=1
>     collapse_key=com.testapp
> 2019-05-27 13:30:28.182 12634-12634/com.testapp D/AppCenterPush: Background notifications are handled by Firebase SDK when integrated.
> 2019-05-27 13:30:28.240 12634-12762/com.testapp W/FirebaseMessaging: Missing Default Notification Channel metadata in AndroidManifest. Default value will be used.

**Comment by Jamminroot** [comment] 2019-05-27 14:01
Hey hey, @wayne1203! Thanks for contacting us. 
Can you please provide code snippets on how you implement this?

**Comment by wayne1203** [comment] 2019-05-28 03:43
Thank you for your help @Jamminroot 
Um... I just follow the instruction in [Doc](https://docs.microsoft.com/en-us/appcenter/sdk/push/react-native-android)

This is my .js added "setListener"
```
import React, { Component } from 'react';
import { createStore } from 'redux';
import { Provider, connect } from 'react-redux'
import rootReducer from './reducers'

import App from './app/index';
import { AppState, Alert } from 'react-native';

import Push from 'appcenter-push';

const store = createStore(rootReducer);

Push.setListener({
  onPushNotificationReceived: function (pushNotification) {
    let message = pushNotification.message;
    let title = pushNotification.title;

    if (message === null) {
      // Android messages received in the background don't include a message. On Android, that fact can be used to
      // check if the message was received in the background or foreground. For iOS the message is always present.
      title = 'Android background';
      message = '<empty>';
    }

    // Custom name/value pairs set in the App Center web portal are in customProperties
    if (pushNotification.customProperties && Object.keys(pushNotification.customProperties).length > 0) {
      message += '\nCustom properties:\n' + JSON.stringify(pushNotification.customProperties);
    }

    if (AppState.currentState === 'active') {
      Alert.alert(title, message);
    }
    else {
      // Sometimes the push callback is received shortly before the app is fully active in the foreground.
      // In this case you'll want to save off the notification info and wait until the app is fully shown
      // in the foreground before displaying any UI. You could use AppState.addEventListener to be notified
      // when the app is fully in the foreground.
    }
  }
});

class MainApp extends Component {

    render() {
        return (
            <Provider store={store}>
                <App />
            </Provider>
        );
    }
}

export default MainApp;
```

And the MainActivity.java
```
package com.testapp;

import com.facebook.react.ReactActivity;
import com.microsoft.appcenter.push.Push;

import android.content.Intent;
import android.os.Bundle; // here
import org.devio.rn.splashscreen.SplashScreen; // here

public class MainActivity extends ReactActivity {

	@Override
    protected void onCreate(Bundle savedInstanceState) {
        SplashScreen.show(this);  // here
        super.onCreate(savedInstanceState);
    }

    @Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        Push.checkLaunchedFromNotification(this, intent);
    }

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "TestApp";
    }
}
```

Also, I added meta-data to manifest for notification icon
```
<meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/ic_noti_icon"
/>
```

**Comment by Jamminroot** [comment] 2019-05-28 11:22
Thanks for sharing your code!
Can you confirm you are receiving message correctly? Does your code fall in to this block
```js
 if (message === null) 
``` 
?

**Comment by wayne1203** [comment] 2019-05-28 15:31
` if (message === null) `
This block will trigger when I click the notification only.

I added a console.log on the top of "onPushNotificationReceived", but it will not print thing when app in background.

**Comment by guperrot** [comment] 2019-05-28 18:12
> `if (message === null)`
> This block will trigger when I click the notification only.
> 
> I added a console.log on the top of "onPushNotificationReceived", but it will not print thing when app in background.

Hi, this is by design and explained in the notes in https://docs.microsoft.com/en-us/appcenter/sdk/push/react-native-android#intercept-push-notifications.

Are you requesting a feature to have the event being fired in background?

**Comment by wayne1203** [comment] 2019-05-29 00:23
@guperrot Thanks for your help.
I would like to have a popup when I received notification in background like Facebook or Whatsapp.

**Comment by guperrot** [comment] 2019-05-29 18:36
Just to be clear you are trying to replace the notification in status bar (would you like it to be hidden?) by something custom like a callback where you design your own UI to show?

**Comment by wayne1203** [comment] 2019-05-30 02:33
I would like to make a notification like [this](https://img.gadgethacks.com/img/original/11/36/63568326326158/0/635683263261581136.jpg)

A pop-up instead of only show a icon in status bar.

**Comment by russelarms** [comment] 2019-05-30 12:51
@wayne1203 Pushes module heavily relies on the Firebase SDK, which has such behavior by default. So I'm afraid such customization is not supported at the moment.

**Comment by guperrot** [comment] 2019-05-30 19:33
Firebase indeed does not support this kind of notifications https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#androidnotification.

What would be needed here is a silent push, then on silent push build a custom local notification from application code.

Unfortunately, silent push for Android is not yet supported.
The silent push is requested here: https://github.com/microsoft/appcenter/issues/87, where you can comment, upvote and track.

**Comment by jruiz666** [comment] 2019-06-03 05:21
Try this.

{
  "notification_content": {
    "name": "your app name",
    "title": "",
    "body": "",
    "custom_data":{"content-available": "1"}
  }
}

**Comment by wayne1203** [comment] 2019-06-03 06:30
@jruiz666 It's not work either. Can I make it work by editing Android Java code?

**Comment by guperrot** [comment] 2019-06-03 18:08
Hi, as explained in https://github.com/microsoft/appcenter-sdk-react-native/issues/583#issuecomment-497456409 the silent push feature is not supported in Android. There is currently no way to make it work using AppCenter Push.

The comment at https://github.com/microsoft/appcenter-sdk-react-native/issues/583#issuecomment-498116457 is incorrect.

**Comment by jmazier-j2d** [comment] 2019-08-17 10:03
I am facing the exact same issue, notifications for Android a**re only displayed in the notification tray** (_as silent notification_). I think what the author of this thread is asking is to be able to display banner just like normal notifications on iOs or Android. Is this caused by a setting in firebase ?

**Comment by jwargo** [comment] 2019-08-22 12:58
We have many customers asking for background notifications and the team is looking into possible solutions.

**Comment by jmazier-j2d** [comment] 2019-08-26 08:35
> We have many customers asking for background notifications and the team is looking into possible solutions.

That would be great, I tried many workaround but no luck till now. Keep us posted ;)

**Comment by jafaronly** [comment] 2019-10-11 07:44
any update please !

**Comment by Jamminroot** [comment] 2019-10-11 09:09
Hey, @jafaronly, @jmazier-j2d, we have this item tracked, but it hasn't been prioritized yet, so there aren't any updates I can provide yet.

**Comment by AnastasiaKubova** [comment] 2021-12-06 10:33
I'm closing this issue since [App Center Push has been removed from the SDK in 4.0.0](https://github.com/microsoft/appcenter-sdk-react-native/blob/develop/CHANGELOG.md#version-400).

**Closed by AnastasiaKubova** 2021-12-06 10:33 UTC
Labels: feature request
