### ISSUE TITLE
Disable autolinking for React Native 0.60 and above

### ISSUE THREAD

**Issue by shariqahmed525** [microsoft/appcenter-sdk-react-native#987] opened 2022-07-17 16:14 UTC
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `appcenter-crashes@4.4.4` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/appcenter-crashes/react-native.config.js b/node_modules/appcenter-crashes/react-native.config.js
index 6b9b1de..b1b2149 100644
--- a/node_modules/appcenter-crashes/react-native.config.js
+++ b/node_modules/appcenter-crashes/react-native.config.js
@@ -3,9 +3,7 @@ const path = require('path');
 module.exports = {
   dependency: {
     platforms: {
-      ios: {
-        podspecPath: path.join(__dirname, 'ios', 'appcenter-crashes.podspec')
-      },
+      ios: null,
       android: {
         packageInstance: 'new AppCenterReactNativeCrashesPackage(getApplication(), getResources().getString(R.string.appCenterCrashes_whenToSendCrashes))'
       }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by AnatolyPristensky** [comment] 2022-07-18 06:54
Hello @shariqahmed525, closing as duplicate of #985

**Closed by AnatolyPristensky** 2022-07-18 06:54 UTC
