### ISSUE TITLE
Recursive header expansion when using other libs such as Firebase

### ISSUE THREAD

**Issue by ethanyuwang** [Microsoft/AppCenter-SDK-React-Native#246] opened 2018-02-21 23:23 UTC
I installed AppCenter and CodePush as instructed. When I tried to compile I encountered this error:

```
Showing Recent Issues
Argument list too long: recursive header expansion failed at /Users/ethanwang/Github/reactnative/Glever_RNI/Glever/node_modules/appcenter/ios/../../../ios/Pods/React/node_modules/fsevents/node_modules/har-validator/lib/node6.
```
Enviroment: 

"react-native": "0.53.0",
node: v8.9.4
cocoapods-1.4.0

I have looked up this error it seems like it was fixed on V1.20 (https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/209)

But I'm still experiencing the same error. How should I fix this?

**Comment by TroubleMakerBen** [comment] 2018-02-22 05:11
Hi @ethanyuwang,

I'd like to help you with this. The title of this issue (*still*) suggests that you had this issue before? I couldn't find it here on Github, can you point me to it, please?

If this is a new issue, can you please provide more context?
* RN version
* Node version (It looks like you are using node 6)
* Cocoapods version
* When does the error happen?

**Comment by ethanyuwang** [comment] 2018-02-22 18:10
@TroubleMakerBen Hi, thank you. I have just updated my issue.

**Comment by ethanyuwang** [comment] 2018-02-24 01:19
Any updates on this?

**Comment by guperrot** [comment] 2018-02-24 01:23
We release cocoapods 1.4.0 support only in our SDK version 1.3.0 and your issue is saying you are using cocoapods 1.4.0.

Can you try on our 1.3.0 SDK?

**Comment by guperrot** [comment] 2018-02-24 01:24
Also we are not compatible with react native 0.53 at the moment. You will have to downgrade temporarily to 0.52 to be able to execute `react-native link` and then update react again after, sorry for the inconvenience

**Comment by BrijeshShiroya** [comment] 2018-02-27 05:51
I had the same issue. I tried to install npm into another system. But still getting same issue. Can you please help me? What is the exact issue?

**Comment by guperrot** [comment] 2018-02-27 21:51
What versions are you using for our SDK and Cocoapods and react-native.

**Comment by dilee716** [comment] 2018-02-27 21:55
I'm having same issues
using `1.3` for SDK,
Cocoapods: `1.4.0`
react-native: `0.52.1`

**Comment by guperrot** [comment] 2018-02-27 22:34
The header search path for app center should not be recursive:

<img width="1055" alt="screen shot 2018-02-26 at 5 59 42 pm" src="https://user-images.githubusercontent.com/623672/36759136-46d14036-1bcb-11e8-9087-526d4b4c5342.png">

Do you have recursive on appcenter headers?

**Comment by dilee716** [comment] 2018-02-27 23:47
they are `not-recursive`

**Comment by guperrot** [comment] 2018-02-27 23:52
but is your error about recursive headers like in the first comment or is it another issue? Please share the exact error message.

**Comment by dilee716** [comment] 2018-02-28 02:16
error is just like first comment.
`Argument list too long: recursive header expansion failed at /Users/dominic/MyAwesomeApp/node_modules/appcenter-analytics/ios/../../../ios/Pods/React/Libraries.`

**Comment by guperrot** [comment] 2018-02-28 02:34
This is a really weird error since you don't use recursive header but complains about recursive, I cannot reproduce here. We will need you to share project sources so we can repro.

**Comment by dilee716** [comment] 2018-02-28 03:14
There are some other headers that are recursive. The appcenter headers are not recursive.
<img width="526" alt="screen shot 2018-02-27 at 10 13 00 pm" src="https://user-images.githubusercontent.com/14097382/36768147-9b63bcc4-1c0b-11e8-92a8-c888180f06c6.png">

**Comment by ethanyuwang** [comment] 2018-03-01 22:51
I'm not very sure if this was the fix since I have tried a lot of different things, but I don't have this error anymore.

Somehow there's another `react` folder in my pods then I deleted it and included this code in my Podfile:

```
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native'
```

Then when running `pod install` the pods won't install a react pod inside the Pods folder but instead, they look for the react folder in node_modules.

**Comment by ethanyuwang** [comment] 2018-03-01 23:34
I think it was needed for react-native-firebase. I did notice `pod install` would install `react-native 0.11`  if I don't have that code in my Podfile when I tried to install appcenter

**Comment by guperrot** [comment] 2018-03-02 00:06
Ok its indeed caused by https://github.com/invertase/react-native-firebase/blob/master/ios/RNFirebase.podspec#L18

**Comment by guperrot** [comment] 2018-03-02 00:08
@dilee716 @BrijeshShiroya do you other 3rd party libs depending on react as pods ? You can look for `React` in `ios/Podfile.lock`, if yes you can follow the steps described in https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/246#issuecomment-369759068 to work around the issue.

**Comment by dilee716** [comment] 2018-03-02 15:08
yeah, currently using other 3rd party libs depending on react as pods. Messing around with it right now. thanks for checking in @guperrot

**Comment by guperrot** [comment] 2018-04-09 18:08
Hi, since we are already importing our own headers as non recursive, there is nothing we can improve that we can think of to avoid the work around.

**Comment by guperrot** [comment] 2018-04-09 18:11
Hi, right now the work around is still needed.

**Comment by dhei** [comment] 2018-05-17 00:31
As a follow up, [v1.5.1](https://github.com/Microsoft/AppCenter-SDK-React-Native/releases/tag/1.5.1) is released today and this issue should be fixed.

Thanks.

**Closed** 2018-05-17 00:34 UTC
Labels: bug
