### ISSUE TITLE
How to control on ask push notification ask (iOS) with AppCenter?

### ISSUE THREAD

**Issue by idanlevi1** [Microsoft/AppCenter-SDK-React-Native#529] opened 2019-02-14 16:45 UTC
Now the pop-up permission show at the first time install on app,
i want to do this only in settings screen.
i use **AppCenter Push** like this:

*AppDelegate.m* i add: 

    #import <AppCenterReactNativePush/AppCenterReactNativePush.h>
and inside `didFinishLaunchingWithOptions` :

    [AppCenterReactNativePush register];  // Initialize AppCenter push

---

*AppCenter-Config.plist*  i add:

    <key>EnablePushInJavascript</key>
	<true/>

----
*package.json*

    "appcenter": "^1.6.0",
    "appcenter-link-scripts": "^1.6.0",
    "appcenter-push": "^1.5.1",

Someone know? or other idea?

***i try to do this on iOS and React Native***

**Comment by MatkovIvan** [comment] 2019-02-18 07:52
Hi @idanlevi1,

Thanks for getting in touch!
This question is duplicate of https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/287#issuecomment-448027977
The feature is released in [1.11.0](https://github.com/Microsoft/AppCenter-SDK-React-Native/releases/tag/1.11.0). Please follow the instructions there or in [the doc](https://docs.microsoft.com/en-us/appcenter/sdk/push/react-native-ios#delay-push-notification-permission-dialog).

Thanks,
Ivan

**Closed by MatkovIvan** 2019-02-18 07:52 UTC
