### ISSUE TITLE
No crash reports appear in AppCenter

### ISSUE THREAD

**Issue by hffmnn** [Microsoft/AppCenter-SDK-React-Native#466] opened 2018-11-20 21:55 UTC
### **Description**

I would like to use the crash reporting feature of AppCenter-SDK-React-Native on iOS. So I followed the setup description for the SDK and the example on how to trigger a crash, described [here](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/react-native).

The problem is, that no crash log appears in the backend.

I sniffed the https traffic with charles and get Status Code 200, basically the same as described here https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/349

I also set a `CrashesListener` and `onSendingSucceeded` gets called.

Things I also made sure:

* The Xcode Debugger is not attached

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Trigger a crash via `Crashes.generateTestCrash()`
2. Restart the application
3. Try to find Crashes in App Center Diagnostics

### **Details**

1. Which version of the App Center SDK are you using?
    - `pod 'AppCenter/Crashes', '~> 1.10.0'`
    - `pod 'AppCenter/Analytics', '~> 1.10.0'`
    - `pod 'AppCenterReactNativeShared', '~> 1.9.0'`
2. Which OS version did you experience the issue on?
    - iOS 12.1
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Tested extensive on iOS Simlator 12.1, iPhone XR
    - Tested on device (without sniffing network traffic and setting the `CrashesListener`
4. What third party libraries are you using?
    - `pod 'Firebase/Core', '~> 5.11.0'`, not used for Crash reporting
5. Run the following command and paste the output below: `react-native info`

```bash
React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 159.79 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: 16.4.18 => 16.4.18
      @types/react-native: 0.57.7 => 0.57.7
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728
      react-native: 0.57.4 => 0.57.4
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

`1.5.3`

7. Please enable verbose logging for your app using `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before your call to `[AppCenterReactNative register];` (or any other SDK registration). For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call. Include the logs here:

This gives the following error:
```
2018-11-20 22:54:25.632847+0100 poc[94651:796109] [AppCenter] DEBUG: -[MSChannelUnitDefault enqueueItem:]_block_invoke/169 Saving log, type: startService.
2018-11-20 22:54:25.634857+0100 poc[94651:796109] [AppCenterCrashes] VERBOSE: -[MSCrashes channel:didCompleteEnqueueingLog:withInternalId:]/494 Deleting a log from buffer with id 673B6B2A-738F-45BB-B556-D8B3C7CB8450
2018-11-20 22:54:28.636698+0100 poc[94651:796107] [AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/237 Sending 1/2 log, group Id: AppCenter, batch Id: 8723DCD3-F465-4108-9C7C-EEB8945D3EF1, session Id: (null), payload:
    "wrapperSdkName" : "appcenter.react-native",
    "sdkName" : "appcenter.ios",
2018-11-20 22:54:28.636881+0100 poc[94651:796107] [AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/237 Sending 2/2 log, group Id: AppCenter, batch Id: 8723DCD3-F465-4108-9C7C-EEB8945D3EF1, session Id: (null), payload:
    "wrapperSdkName" : "appcenter.react-native",
    "sdkName" : "appcenter.ios",
2018-11-20 22:54:28.637214+0100 poc[94651:796107] [AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:]/90 URL: https://in.appcenter.ms/logs?api-version=1.0.0
2018-11-20 22:54:28.637352+0100 poc[94651:796107] [AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:]/91 Headers: Install-ID = B31E922F-806D-4607-91D9-D9B8735A6344, App-Secret = ****************************01162407, Content-Type = application/json
2018-11-20 22:54:29.195500+0100 poc[94651:796093] [AppCenter] VERBOSE: -[MSHttpIngestion sendCallAsync:]_block_invoke/234 HTTP response received with status code: 200, payload:
2018-11-20 22:54:29.195631+0100 poc[94651:796093] [AppCenter] INFO: -[MSHttpIngestion call:completedWithResult:]/283 Removed call id:8723DCD3-F465-4108-9C7C-EEB8945D3EF1 from pending calls:{
2018-11-20 22:54:29.195634+0100 poc[94651:796094] [AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/258 Log(s) sent with success, batch Id:8723DCD3-F465-4108-9C7C-EEB8945D3EF1.
2018-11-20 22:54:29.197603+0100 poc[94651:796094] [AppCenter] VERBOSE: -[MSLogDBStorage deleteLogsFromDBWithColumnValues:columnName:]/268 Deletion of log(s) by id with value(s) '76','77' succeeded.
```

**Comment by achocron** [comment] 2018-11-20 22:03
Is the output you pasted at the end printed in a scenario where a crash is being sent? If so, it looks like some lines are missing. Can you please try reproducing the scenario and send the logs that appear when the app is restarted (after crashing)? Thanks!

**Comment by hffmnn** [comment] 2018-11-20 22:11
Hi and thanks for the quick answer.

I let the app crash and restarted it without the debugger attached. This are the resulting logs:

```bash
2018-11-20 23:07:47.692588+0100 poc[95509:819132] [AppCenterCrashes] VERBOSE: -[MSCrashes channel:didCompleteEnqueueingLog:withInternalId:]/494 Deleting a log from buffer with id 9004B556-384D-4773-B090-3D3CFDBFAB68
2018-11-20 23:07:47.694637+0100 poc[95509:819132] [AppCenter] VERBOSE: -[MSChannelUnitDefault resumeWithIdentifyingObjectSync:]/442 Identifying object <MSAnalytics: 0x600001ca58f0> removed from pause lane for channel Analytics.
2018-11-20 23:07:47.694818+0100 poc[95509:819132] [AppCenter] DEBUG: -[MSChannelUnitDefault resumeWithIdentifyingObjectSync:]/444 Resume channel Analytics.
2018-11-20 23:07:47.695756+0100 poc[95509:819132] [AppCenter] DEBUG: -[MSChannelUnitDefault enqueueItem:]_block_invoke/169 Saving log, type: startSession.
2018-11-20 23:07:47.697956+0100 poc[95509:819132] [AppCenter] DEBUG: -[MSChannelUnitDefault enqueueItem:]_block_invoke/169 Saving log, type: startService.
2018-11-20 23:07:47.699819+0100 poc[95509:819132] [AppCenterCrashes] VERBOSE: -[MSCrashes channel:didCompleteEnqueueingLog:withInternalId:]/494 Deleting a log from buffer with id 59DB6CAD-3E3E-4F74-91B3-D02D0A487BDA
2018-11-20 23:07:47.700047+0100 poc[95509:819132] [AppCenter] VERBOSE: -[MSChannelUnitDefault resumeWithIdentifyingObjectSync:]/442 Identifying object <MSAnalytics: 0x600001ca58f0> removed from pause lane for channel Analytics/one.
2018-11-20 23:07:47.700209+0100 poc[95509:819132] [AppCenter] DEBUG: -[MSChannelUnitDefault resumeWithIdentifyingObjectSync:]/444 Resume channel Analytics/one.
2018-11-20 23:07:48.701419+0100 poc[95509:819142] [AppCenterCrashes] DEBUG: -[MSCrashes startCrashProcessing]/656 Start delayed CrashManager processing
2018-11-20 23:07:48.717733+0100 poc[95509:819142] [AppCenterCrashes] VERBOSE: -[MSCrashes processCrashReports]/715 Crash reports found
2018-11-20 23:07:48.731041+0100 poc[95509:819142] [AppCenterCrashes] DEBUG: -[MSCrashes processCrashReports]/725 shouldProcessErrorReport is not implemented or returned YES, processing the crash report: <MSPLCrashReport: 0x6000013be3a0>
2018-11-20 23:07:48.731184+0100 poc[95509:819142] [AppCenterCrashes] DEBUG: -[MSCrashes sendCrashReportsOrAwaitUserConfirmation]/1056 The user confirmation handler is not implemented or returned NO, continue sending logs
2018-11-20 23:07:48.731299+0100 poc[95509:819142] [AppCenterCrashes] DEBUG: -[MSCrashes notifyWithUserConfirmation:]/1130 attachmentsWithCrashes is not implemented
2018-11-20 23:07:48.731667+0100 poc[95509:819124] [AppCenter] DEBUG: -[MSChannelUnitDefault enqueueItem:]_block_invoke/169 Saving log, type: appleError.
2018-11-20 23:07:48.734014+0100 poc[95509:819142] [AppCenter] DEBUG: +[MSUtility(File) deleteItemForPathComponent:]/56 Couldn't remove item at file:///Users/christian/Library/Developer/CoreSimulator/Devices/6CDE8597-20E5-43AD-8CB8-C31C552BA8A3/data/Containers/Data/Application/20995C43-E1AC-4747-A32A-0FB6630E3E48/Library/Application%20Support/com.microsoft.appcenter/crasheswrapperexceptions/814DDC7A-2951-4C42-8915-16C5253FD8DE: “814DDC7A-2951-4C42-8915-16C5253FD8DE” couldn’t be removed.
2018-11-20 23:07:48.734780+0100 poc[95509:819142] [AppCenter] VERBOSE: -[MSSessionContext clearSessionHistory]/83 Cleared old sessions.
2018-11-20 23:07:48.736851+0100 poc[95509:819137] [AppCenterCrashes] DEBUG: -[MSCrashes sendCrashReportsOrAwaitUserConfirmation]/1056 The user confirmation handler is not implemented or returned NO, continue sending logs
2018-11-20 23:07:48.736977+0100 poc[95509:819137] [AppCenterCrashes] DEBUG: -[MSCrashes notifyWithUserConfirmation:]/1130 attachmentsWithCrashes is not implemented
2018-11-20 23:07:48.737612+0100 poc[95509:819137] [AppCenter] DEBUG: +[MSUtility(File) deleteFileAtURL:]/78 Couldn't remove item at file:///Users/christian/Library/Developer/CoreSimulator/Devices/6CDE8597-20E5-43AD-8CB8-C31C552BA8A3/data/Containers/Data/Application/20995C43-E1AC-4747-A32A-0FB6630E3E48/Library/Application%20Support/com.microsoft.appcenter/crashes/564444468: “564444468” couldn’t be removed.
2018-11-20 23:07:48.737884+0100 poc[95509:819137] [AppCenter] DEBUG: +[MSUtility(File) deleteItemForPathComponent:]/56 Couldn't remove item at file:///Users/christian/Library/Developer/CoreSimulator/Devices/6CDE8597-20E5-43AD-8CB8-C31C552BA8A3/data/Containers/Data/Application/20995C43-E1AC-4747-A32A-0FB6630E3E48/Library/Application%20Support/com.microsoft.appcenter/crasheswrapperexceptions/814DDC7A-2951-4C42-8915-16C5253FD8DE: “814DDC7A-2951-4C42-8915-16C5253FD8DE” couldn’t be removed.
2018-11-20 23:07:48.738084+0100 poc[95509:819137] [AppCenter] VERBOSE: -[MSSessionContext clearSessionHistory]/83 Cleared old sessions.
2018-11-20 23:07:48.738851+0100 poc[95509:819137] [AppCenterCrashes] DEBUG: -[MSCrashes notifyWithUserConfirmation:]/1130 attachmentsWithCrashes is not implemented
2018-11-20 23:07:48.739166+0100 poc[95509:819137] [AppCenter] DEBUG: +[MSUtility(File) deleteFileAtURL:]/78 Couldn't remove item at file:///Users/christian/Library/Developer/CoreSimulator/Devices/6CDE8597-20E5-43AD-8CB8-C31C552BA8A3/data/Containers/Data/Application/20995C43-E1AC-4747-A32A-0FB6630E3E48/Library/Application%20Support/com.microsoft.appcenter/crashes/564444468: “564444468” couldn’t be removed.
2018-11-20 23:07:48.739445+0100 poc[95509:819137] [AppCenter] DEBUG: +[MSUtility(File) deleteItemForPathComponent:]/56 Couldn't remove item at file:///Users/christian/Library/Developer/CoreSimulator/Devices/6CDE8597-20E5-43AD-8CB8-C31C552BA8A3/data/Containers/Data/Application/20995C43-E1AC-4747-A32A-0FB6630E3E48/Library/Application%20Support/com.microsoft.appcenter/crasheswrapperexceptions/814DDC7A-2951-4C42-8915-16C5253FD8DE: “814DDC7A-2951-4C42-8915-16C5253FD8DE” couldn’t be removed.
2018-11-20 23:07:48.739658+0100 poc[95509:819137] [AppCenter] VERBOSE: -[MSSessionContext clearSessionHistory]/83 Cleared old sessions.
2018-11-20 23:07:48.765098+0100 poc[95509:819124] [AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/237 Sending 1/1 log, group Id: Crashes, batch Id: 3205790D-BFB1-4687-93D3-E94E917E8434, session Id: EEE67592-2B67-4EA3-9D99-794BD61CAA89, payload:
     sdkName: 'appcenter.ios',
     sdkName: 'appcenter.ios',
2018-11-20 23:07:48.778852+0100 poc[95509:819124] [AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:]/90 URL: https://in.appcenter.ms/logs?api-version=1.0.0
2018-11-20 23:07:48.779042+0100 poc[95509:819124] [AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:]/91 Headers: Content-Encoding = gzip, Install-ID = 7BC5386A-29C2-4E90-A0A1-7DA7B58F8ACA, App-Secret = ****************************01162407, Content-Type = application/json
2018-11-20 23:07:48.779788+0100 poc[95509:819124] [AppCenter] DEBUG: -[MSChannelUnitDefault enqueueItem:]_block_invoke/169 Saving log, type: appleError.
2018-11-20 23:07:48.801462+0100 poc[95509:819124] [AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/237 Sending 1/1 log, group Id: Crashes, batch Id: 74F79582-7AB2-497A-8315-B305A3D202DE, session Id: (null), payload:
     sdkName: 'appcenter.ios',
     sdkName: 'appcenter.ios',
2018-11-20 23:07:48.829836+0100 poc[95509:819124] [AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:]/90 URL: https://in.appcenter.ms/logs?api-version=1.0.0
2018-11-20 23:07:48.830001+0100 poc[95509:819124] [AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:]/91 Headers: Content-Encoding = gzip, Install-ID = 7BC5386A-29C2-4E90-A0A1-7DA7B58F8ACA, App-Secret = ****************************01162407, Content-Type = application/json
2018-11-20 23:07:48.830356+0100 poc[95509:819124] [AppCenter] DEBUG: -[MSChannelUnitDefault enqueueItem:]_block_invoke/169 Saving log, type: appleError.
2018-11-20 23:07:48.853003+0100 poc[95509:819124] [AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/237 Sending 1/1 log, group Id: Crashes, batch Id: C75B3603-5F77-4256-B12E-EDAC67246FF3, session Id: (null), payload:
     sdkName: 'appcenter.ios',
     sdkName: 'appcenter.ios',
2018-11-20 23:07:48.865529+0100 poc[95509:819124] [AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:]/90 URL: https://in.appcenter.ms/logs?api-version=1.0.0
2018-11-20 23:07:48.865676+0100 poc[95509:819124] [AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:]/91 Headers: Content-Encoding = gzip, Install-ID = 7BC5386A-29C2-4E90-A0A1-7DA7B58F8ACA, App-Secret = ****************************01162407, Content-Type = application/json
2018-11-20 23:07:49.645391+0100 poc[95509:819137] [AppCenter] VERBOSE: -[MSHttpIngestion sendCallAsync:]_block_invoke/234 HTTP response received with status code: 200, payload:
2018-11-20 23:07:49.645716+0100 poc[95509:819142] [AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/258 Log(s) sent with success, batch Id:3205790D-BFB1-4687-93D3-E94E917E8434.
2018-11-20 23:07:49.645806+0100 poc[95509:819137] [AppCenter] INFO: -[MSHttpIngestion call:completedWithResult:]/283 Removed call id:3205790D-BFB1-4687-93D3-E94E917E8434 from pending calls:{
     sdkName: 'appcenter.ios',
     sdkName: 'appcenter.ios',
2018-11-20 23:07:49.654553+0100 poc[95509:819142] [AppCenter] VERBOSE: -[MSLogDBStorage deleteLogsFromDBWithColumnValues:columnName:]/268 Deletion of log(s) by id with value(s) '7' succeeded.
2018-11-20 23:07:50.069974+0100 poc[95509:819137] [AppCenter] VERBOSE: -[MSHttpIngestion sendCallAsync:]_block_invoke/234 HTTP response received with status code: 200, payload:
2018-11-20 23:07:50.070202+0100 poc[95509:819124] [AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/258 Log(s) sent with success, batch Id:C75B3603-5F77-4256-B12E-EDAC67246FF3.
2018-11-20 23:07:50.070207+0100 poc[95509:819137] [AppCenter] INFO: -[MSHttpIngestion call:completedWithResult:]/283 Removed call id:C75B3603-5F77-4256-B12E-EDAC67246FF3 from pending calls:{
     sdkName: 'appcenter.ios',
     sdkName: 'appcenter.ios',
2018-11-20 23:07:50.079514+0100 poc[95509:819124] [AppCenter] VERBOSE: -[MSLogDBStorage deleteLogsFromDBWithColumnValues:columnName:]/268 Deletion of log(s) by id with value(s) '9' succeeded.
2018-11-20 23:07:50.092818+0100 poc[95509:819124] [AppCenter] VERBOSE: -[MSHttpIngestion sendCallAsync:]_block_invoke/234 HTTP response received with status code: 200, payload:
2018-11-20 23:07:50.093011+0100 poc[95509:819124] [AppCenter] INFO: -[MSHttpIngestion call:completedWithResult:]/283 Removed call id:74F79582-7AB2-497A-8315-B305A3D202DE from pending calls:{
2018-11-20 23:07:50.093011+0100 poc[95509:819142] [AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/258 Log(s) sent with success, batch Id:74F79582-7AB2-497A-8315-B305A3D202DE.
     sdkName: 'appcenter.ios',
     sdkName: 'appcenter.ios',
2018-11-20 23:07:50.096415+0100 poc[95509:819142] [AppCenter] VERBOSE: -[MSLogDBStorage deleteLogsFromDBWithColumnValues:columnName:]/268 Deletion of log(s) by id with value(s) '8' succeeded.
2018-11-20 23:07:50.701805+0100 poc[95509:819142] [AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/237 Sending 1/1 log, group Id: Analytics, batch Id: A820200B-F282-48DD-B514-D9DC9B8A7669, session Id: B6EED256-45A7-4B4F-B294-2662673D67B8, payload:
    "wrapperSdkName" : "appcenter.react-native",
    "sdkName" : "appcenter.ios",
2018-11-20 23:07:50.702206+0100 poc[95509:819142] [AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:]/90 URL: https://in.appcenter.ms/logs?api-version=1.0.0
2018-11-20 23:07:50.702446+0100 poc[95509:819142] [AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:]/91 Headers: Install-ID = 7BC5386A-29C2-4E90-A0A1-7DA7B58F8ACA, App-Secret = ****************************01162407, Content-Type = application/json
2018-11-20 23:07:50.704203+0100 poc[95509:819142] [AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/237 Sending 1/2 log, group Id: AppCenter, batch Id: 9EC2CBC5-9851-4EA1-B1D6-A3687D305495, session Id: (null), payload:
    "wrapperSdkName" : "appcenter.react-native",
    "sdkName" : "appcenter.ios",
2018-11-20 23:07:50.704433+0100 poc[95509:819142] [AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/237 Sending 2/2 log, group Id: AppCenter, batch Id: 9EC2CBC5-9851-4EA1-B1D6-A3687D305495, session Id: (null), payload:
    "wrapperSdkName" : "appcenter.react-native",
    "sdkName" : "appcenter.ios",
2018-11-20 23:07:50.710478+0100 poc[95509:819142] [AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:]/90 URL: https://in.appcenter.ms/logs?api-version=1.0.0
2018-11-20 23:07:50.710676+0100 poc[95509:819142] [AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:]/91 Headers: Install-ID = 7BC5386A-29C2-4E90-A0A1-7DA7B58F8ACA, App-Secret = ****************************01162407, Content-Type = application/json
2018-11-20 23:07:50.840796+0100 poc[95509:819124] [AppCenter] VERBOSE: -[MSHttpIngestion sendCallAsync:]_block_invoke/234 HTTP response received with status code: 200, payload:
2018-11-20 23:07:50.841054+0100 poc[95509:819132] [AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/258 Log(s) sent with success, batch Id:9EC2CBC5-9851-4EA1-B1D6-A3687D305495.
2018-11-20 23:07:50.841073+0100 poc[95509:819124] [AppCenter] INFO: -[MSHttpIngestion call:completedWithResult:]/283 Removed call id:9EC2CBC5-9851-4EA1-B1D6-A3687D305495 from pending calls:{
2018-11-20 23:07:50.841311+0100 poc[95509:819137] [AppCenter] VERBOSE: -[MSHttpIngestion sendCallAsync:]_block_invoke/234 HTTP response received with status code: 200, payload:
2018-11-20 23:07:50.841495+0100 poc[95509:819137] [AppCenter] INFO: -[MSHttpIngestion call:completedWithResult:]/283 Removed call id:A820200B-F282-48DD-B514-D9DC9B8A7669 from pending calls:{
2018-11-20 23:07:50.844205+0100 poc[95509:819132] [AppCenter] VERBOSE: -[MSLogDBStorage deleteLogsFromDBWithColumnValues:columnName:]/268 Deletion of log(s) by id with value(s) '4','6' succeeded.
2018-11-20 23:07:50.844363+0100 poc[95509:819132] [AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/258 Log(s) sent with success, batch Id:A820200B-F282-48DD-B514-D9DC9B8A7669.
2018-11-20 23:07:50.846101+0100 poc[95509:819132] [AppCenter] VERBOSE: -[MSLogDBStorage deleteLogsFromDBWithColumnValues:columnName:]/268 Deletion of log(s) by id with value(s) '5' succeeded.

```

**Comment by achocron** [comment] 2018-11-21 01:08
Thanks for that! So it's looking like this might be a backend issue rather than SDK side issue, so to make sure the right person helps you out, do you mind moving this conversation to Intercom? To do that, just press the blue button in the lower left corner of the portal and describe your issue in the chat. (And please include the info you provided here! Or just link this issue.) Thanks so much!

**Closed by achocron** 2018-11-21 01:08 UTC

**Comment by hffmnn** [comment] 2018-11-21 08:38
Thanks for the info. Will do!

**Comment by PaulsonMac** [comment] 2019-06-21 12:52
Hi @hffmnn, may I know how did you get this solved..? Thanks

**Comment by PaulsonMac** [comment] 2019-07-04 09:31
@hffmnn, ok.. not a problem 👍  Thanks!

**Comment by Jamminroot** [comment] 2019-07-08 14:22
@PaulsonMac feel free to get in touch with via intercom ticket if you need any assistance.
To do so, click support button in the corner of appcenter portal

**Comment by RakeshYadvanshi** [comment] 2020-04-01 15:50
> @PaulsonMac Sorry, but I can not remember. As far as I can remember I informed the backend team via Intercom, but can not remember the outcome (mainly because we no longer use RN and AppCenter).

so you basically resolved by removing the app center from application :)
