### ISSUE TITLE
Duplicate resources in build

### ISSUE THREAD

**Issue by ecatugy** [microsoft/appcenter-sdk-react-native#830] opened 2020-05-21 13:06 UTC
I have problems when run build in AppCenter, at step: 
app:mergeReleaseResources:
 
* What went wrong:
Execution failed for task ':app:mergeReleaseResources'.
> [drawable-xhdpi-v4/app_images_yourapp] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-xhdpi/app_images_yourapp.png	[drawable-xhdpi-v4/app_images_yourapp] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-xhdpi-v4/app_images_yourapp.png: Error: Duplicate resources
  [drawable-xhdpi-v4/app_images_launchicon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-xhdpi/app_images_launchicon.png	[drawable-xhdpi-v4/app_images_launchicon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-xhdpi-v4/app_images_launchicon.png: Error: Duplicate resources
  [drawable-xhdpi-v4/node_modules_reactnavigationstack_lib_module_views_assets_backicon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-xhdpi/node_modules_reactnavigationstack_lib_module_views_assets_backicon.png	[drawable-xhdpi-v4/node_modules_reactnavigationstack_lib_module_views_assets_backicon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-xhdpi-v4/node_modules_reactnavigationstack_lib_module_views_assets_backicon.png: Error: Duplicate resources
  [drawable-xxhdpi-v4/app_images_yourapp] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-xxhdpi/app_images_yourapp.png	[drawable-xxhdpi-v4/app_images_yourapp] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-xxhdpi-v4/app_images_yourapp.png: Error: Duplicate resources
  [drawable-xxhdpi-v4/app_images_launchicon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-xxhdpi/app_images_launchicon.png	[drawable-xxhdpi-v4/app_images_launchicon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-xxhdpi-v4/app_images_launchicon.png: Error: Duplicate resources
  [drawable-xxhdpi-v4/node_modules_reactnavigationstack_lib_module_views_assets_backicon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-xxhdpi/node_modules_reactnavigationstack_lib_module_views_assets_backicon.png	[drawable-xxhdpi-v4/node_modules_reactnavigationstack_lib_module_views_assets_backicon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-xxhdpi-v4/node_modules_reactnavigationstack_lib_module_views_assets_backicon.png: Error: Duplicate resources
  [drawable-hdpi-v4/node_modules_reactnavigationstack_lib_module_views_assets_backicon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-hdpi/node_modules_reactnavigationstack_lib_module_views_assets_backicon.png	[drawable-hdpi-v4/node_modules_reactnavigationstack_lib_module_views_assets_backicon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-hdpi-v4/node_modules_reactnavigationstack_lib_module_views_assets_backicon.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_list_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_list_icon.png	[drawable-mdpi-v4/app_images_list_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_list_icon.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_arrow_up_icon_disabled] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_arrow_up_icon_disabled.png	[drawable-mdpi-v4/app_images_arrow_up_icon_disabled] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_arrow_up_icon_disabled.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_plus_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_plus_icon.png	[drawable-mdpi-v4/app_images_plus_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_plus_icon.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_catalogo_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_catalogo_icon.png	[drawable-mdpi-v4/app_images_catalogo_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_catalogo_icon.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_arrow_up_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_arrow_up_icon.png	[drawable-mdpi-v4/app_images_arrow_up_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_arrow_up_icon.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_email_send_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_email_send_icon.png	[drawable-mdpi-v4/app_images_email_send_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_email_send_icon.png: Error: Duplicate resources
  [drawable-mdpi-v4/node_modules_reactnativeelements_src_rating_images_bell] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/node_modules_reactnativeelements_src_rating_images_bell.png	[drawable-mdpi-v4/node_modules_reactnativeelements_src_rating_images_bell] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/node_modules_reactnativeelements_src_rating_images_bell.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_save_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_save_icon.png	[drawable-mdpi-v4/app_images_save_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_save_icon.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_cotacao_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_cotacao_icon.png	[drawable-mdpi-v4/app_images_cotacao_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_cotacao_icon.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_bg] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_bg.png	[drawable-mdpi-v4/app_images_bg] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_bg.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_yourapp] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_yourapp.png	[drawable-mdpi-v4/app_images_yourapp] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_yourapp.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_email_lido] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_email_lido.png	[drawable-mdpi-v4/app_images_email_lido] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_email_lido.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_mensagem_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_mensagem_icon.png	[drawable-mdpi-v4/app_images_mensagem_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_mensagem_icon.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_close_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_close_icon.png	[drawable-mdpi-v4/app_images_close_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_close_icon.png: Error: Duplicate resources
  [drawable-mdpi-v4/node_modules_reactnavigationstack_lib_module_views_assets_backiconmask] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/node_modules_reactnavigationstack_lib_module_views_assets_backiconmask.png	[drawable-mdpi-v4/node_modules_reactnavigationstack_lib_module_views_assets_backiconmask] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/node_modules_reactnavigationstack_lib_module_views_assets_backiconmask.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_empresa_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_empresa_icon.png	[drawable-mdpi-v4/app_images_empresa_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_empresa_icon.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_arrow_down_icon_disabled] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_arrow_down_icon_disabled.png	[drawable-mdpi-v4/app_images_arrow_down_icon_disabled] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_arrow_down_icon_disabled.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_pedido_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_pedido_icon.png	[drawable-mdpi-v4/app_images_pedido_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_pedido_icon.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_requisicao_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_requisicao_icon.png	[drawable-mdpi-v4/app_images_requisicao_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_requisicao_icon.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_share] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_share.png	[drawable-mdpi-v4/app_images_share] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_share.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_search_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_search_icon.png	[drawable-mdpi-v4/app_images_search_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_search_icon.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_icon.png	[drawable-mdpi-v4/app_images_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_icon.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_checkmark_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_checkmark_icon.png	[drawable-mdpi-v4/app_images_checkmark_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_checkmark_icon.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_nota_fiscal_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_nota_fiscal_icon.png	[drawable-mdpi-v4/app_images_nota_fiscal_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_nota_fiscal_icon.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_ellipsis_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_ellipsis_icon.png	[drawable-mdpi-v4/app_images_ellipsis_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_ellipsis_icon.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_sem_filtro] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_sem_filtro.png	[drawable-mdpi-v4/app_images_sem_filtro] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_sem_filtro.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_arrow_down_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_arrow_down_icon.png	[drawable-mdpi-v4/app_images_arrow_down_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_arrow_down_icon.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_filter_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_filter_icon.png	[drawable-mdpi-v4/app_images_filter_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_filter_icon.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_informe_filtro] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_informe_filtro.png	[drawable-mdpi-v4/app_images_informe_filtro] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_informe_filtro.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_contrato_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_contrato_icon.png	[drawable-mdpi-v4/app_images_contrato_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_contrato_icon.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_email_nao_lido] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_email_nao_lido.png	[drawable-mdpi-v4/app_images_email_nao_lido] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_email_nao_lido.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_launchicon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_launchicon.png	[drawable-mdpi-v4/app_images_launchicon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_launchicon.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_360_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_360_icon.png	[drawable-mdpi-v4/app_images_360_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_360_icon.png: Error: Duplicate resources
  [drawable-mdpi-v4/node_modules_reactnativeelements_src_rating_images_rocket] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/node_modules_reactnativeelements_src_rating_images_rocket.png	[drawable-mdpi-v4/node_modules_reactnativeelements_src_rating_images_rocket] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/node_modules_reactnativeelements_src_rating_images_rocket.png: Error: Duplicate resources
  [drawable-mdpi-v4/node_modules_reactnativeelements_src_rating_images_heart] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/node_modules_reactnativeelements_src_rating_images_heart.png	[drawable-mdpi-v4/node_modules_reactnativeelements_src_rating_images_heart] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/node_modules_reactnativeelements_src_rating_images_heart.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_up_down_arrow_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_up_down_arrow_icon.png	[drawable-mdpi-v4/app_images_up_down_arrow_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_up_down_arrow_icon.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_person_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_person_icon.png	[drawable-mdpi-v4/app_images_person_icon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_person_icon.png: Error: Duplicate resources
  [drawable-mdpi-v4/node_modules_reactnativeelements_src_rating_images_star] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/node_modules_reactnativeelements_src_rating_images_star.png	[drawable-mdpi-v4/node_modules_reactnativeelements_src_rating_images_star] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/node_modules_reactnativeelements_src_rating_images_star.png: Error: Duplicate resources
  [drawable-mdpi-v4/app_images_360_image] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/app_images_360_image.png	[drawable-mdpi-v4/app_images_360_image] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/app_images_360_image.png: Error: Duplicate resources
  [drawable-mdpi-v4/node_modules_reactnavigationstack_lib_module_views_assets_backicon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-mdpi/node_modules_reactnavigationstack_lib_module_views_assets_backicon.png	[drawable-mdpi-v4/node_modules_reactnavigationstack_lib_module_views_assets_backicon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-mdpi-v4/node_modules_reactnavigationstack_lib_module_views_assets_backicon.png: Error: Duplicate resources
  [drawable-xxxhdpi-v4/node_modules_reactnavigationstack_lib_module_views_assets_backicon] /Users/runner/runners/2.168.2/work/1/s/android/app/src/main/res/drawable-xxxhdpi/node_modules_reactnavigationstack_lib_module_views_assets_backicon.png	[drawable-xxxhdpi-v4/node_modules_reactnavigationstack_lib_module_views_assets_backicon] /Users/runner/runners/2.168.2/work/1/s/android/app/build/generated/res/react/release/drawable-xxxhdpi-v4/node_modules_reactnavigationstack_lib_module_views_assets_backicon.png: Error: Duplicate resources

 App Center SDK :
    "appcenter": "1.10.0",
    "appcenter-analytics": "1.10.0",
    "appcenter-crashes": "1.10.0",
    "appcenter-push": "^1.10.0",

React Native:
    "react": "16.8.3",
    "react-native": "0.59.10"

Node:
  v - 12.6.0

build.gradle

buildscript {
    ext {
        googlePlayServicesVersion = '16.+'
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.0'
        classpath 'com.google.gms:google-services:4.2.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

Has anyone ever experienced this ?

**Comment by MatkovIvan** [comment] 2020-05-21 15:48
Hi @ecatugy,

It doesn't look like App Center SDK issue. As mentioned in the issue template (that was removed on creating):

> Please create issues only for problems specific to using the SDK for React Native.
    If your issue is related to App Center build only (meaning no issue building locally) or CodePush,
    please create an issue on https://github.com/Microsoft/appcenter instead.

So, I'm going to close this. If you still think that the issue is related to this SDK, feel free to reply here, but please make sure the issue template has been filled properly.

Also, you can try some solutions in similar issues outside of App Center. For example: https://github.com/facebook/react-native/issues/26245

**Closed by MatkovIvan** 2020-05-21 15:48 UTC
Labels: support
